"""Descriptions pédagogiques pour les 118 éléments.
Champs : occurrence (où le trouver), specificity (spécificités),
uses (utilisations principales), role (rôle).
"""

DESCRIPTIONS = {
    1: {
        "occurrence": "Élément le plus abondant de l'univers (~75% de la masse baryonique). Sur Terre, présent surtout sous forme d'eau (H₂O), d'hydrocarbures et de matière organique.",
        "specificity": "Atome le plus léger et le plus simple : un proton, un électron. Trois isotopes : ¹H (protium), ²H (deutérium), ³H (tritium, radioactif).",
        "uses": ["Synthèse d'ammoniac (procédé Haber-Bosch)", "Hydrocraquage pétrolier", "Pile à combustible (mobilité décarbonée)", "Soudure"],
        "role": "Constituant essentiel de l'eau et des biomolécules ; vecteur-clé de la transition énergétique.",
    },
    2: {
        "occurrence": "2ᵉ élément le plus abondant de l'univers. Sur Terre, piégé dans certains gisements de gaz naturel (États-Unis, Algérie, Qatar, Russie).",
        "specificity": "Gaz noble le plus inerte ; point d'ébullition le plus bas (−269 °C). Ne se solidifie pas à 0 K sous pression normale (anomalie quantique).",
        "uses": ["Refroidissement IRM (hélium liquide)", "Ballons et dirigeables", "Gaz porteur en chromatographie", "Atmosphère inerte pour la soudure"],
        "role": "Ressource critique en cryogénie et imagerie médicale, dont les réserves s'épuisent rapidement.",
    },
    3: {
        "occurrence": "Saumures du « triangle du lithium » (Bolivie, Chili, Argentine - salar d'Uyuni, Atacama) et pegmatites (Australie, Chine, Zimbabwe).",
        "specificity": "Métal le plus léger ; solide de plus faible densité (0,534 g/cm³). Se conserve sous huile car réagit violemment avec l'eau.",
        "uses": ["Batteries lithium-ion (smartphones, véhicules électriques)", "Médicament (régulateur thymique)", "Verres et céramiques", "Lubrifiants"],
        "role": "Pilier industriel de l'électrification des transports - pétrole blanc du XXIᵉ siècle.",
    },
    4: {
        "occurrence": "Béryl (silicate de béryllium) et émeraude (béryl coloré par le chrome). Extraction principale au Brésil, États-Unis, Chine.",
        "specificity": "Très toxique (béryliose pulmonaire) mais remarquablement transparent aux rayons X et 33% plus rigide que l'acier pour 1/4 du poids.",
        "uses": ["Fenêtres de tubes à rayons X", "Alliages aérospatiaux (Cu-Be)", "Réflecteur de neutrons en réacteur nucléaire", "Miroirs spatiaux (JWST)"],
        "role": "Métallurgie de très haute performance, applications nucléaires et aérospatiales.",
    },
    5: {
        "occurrence": "Borax et kernite dans les déserts (Californie, Turquie). Concentré dans les évaporites des anciens lacs salins.",
        "specificity": "Métalloïde au comportement chimique unique (liaisons électron-déficitaires, clusters). Excellent absorbeur de neutrons (¹⁰B).",
        "uses": ["Verre borosilicaté (Pyrex)", "Détergents (perborate)", "Engrais (oligo-élément)", "Contrôle des réacteurs nucléaires"],
        "role": "Oligo-élément essentiel aux plantes ; matériau de pointe en céramique et nucléaire.",
    },
    6: {
        "occurrence": "Omniprésent sur Terre : matière organique vivante et fossile (charbon, pétrole, gaz), CO₂ atmosphérique, carbonates (calcaire).",
        "specificity": "Forme plus de composés que tous les autres éléments combinés. Allotropes spectaculaires : diamant, graphite, fullerènes, nanotubes, graphène.",
        "uses": ["Acier (alliage Fe-C)", "Combustibles fossiles", "Plastiques et polymères", "Électronique (graphène, nanotubes)"],
        "role": "Squelette de la chimie organique et de toute la matière vivante.",
    },
    7: {
        "occurrence": "78% de l'atmosphère terrestre. Nitrates (Chili), ammoniac biosynthétisé, protéines et acides nucléiques.",
        "specificity": "Triple liaison N≡N extrêmement stable rend N₂ quasi-inerte. Énergie de dissociation 945 kJ/mol - une des plus élevées.",
        "uses": ["Engrais azotés (ammoniac via Haber-Bosch)", "Explosifs (TNT, nitroglycérine)", "Conservation cryogénique (N₂ liquide)", "Atmosphère inerte industrielle"],
        "role": "Constituant des protéines et de l'ADN ; clé de l'agriculture mondiale.",
    },
    8: {
        "occurrence": "21% de l'atmosphère. Élément le plus abondant de la croûte terrestre (47%) - silicates, oxydes, eau.",
        "specificity": "Paramagnétique (les autres gaz courants sont diamagnétiques). Existe en O₂ (dioxygène) et O₃ (ozone, protège des UV en stratosphère).",
        "uses": ["Respiration cellulaire", "Sidérurgie (haut-fourneau)", "Médecine (oxygénothérapie)", "Traitement de l'eau"],
        "role": "Indispensable à la vie aérobie et à toute combustion.",
    },
    9: {
        "occurrence": "Fluorite (CaF₂), cryolite (Groenland historiquement), apatite. Concentré au Mexique, en Chine et en Mongolie.",
        "specificity": "Élément le plus électronégatif (3,98 Pauling) et le plus réactif. Attaque le verre, brûle l'eau, oxyde même l'or finement divisé.",
        "uses": ["Dentifrice (fluorures, prévention des caries)", "Téflon (PTFE)", "Fluides frigorigènes", "Enrichissement de l'uranium (UF₆)"],
        "role": "Chimie industrielle moderne - fluoration, plastiques techniques, pharmacie.",
    },
    10: {
        "occurrence": "Présent dans l'atmosphère à 18 ppm seulement. Produit industriellement par liquéfaction-distillation de l'air.",
        "specificity": "4ᵉ élément le plus abondant de l'univers, presque absent sur Terre car trop léger pour être retenu par la gravité.",
        "uses": ["Enseignes lumineuses (décharge rouge-orangé caractéristique)", "Laser He-Ne", "Indicateurs haute tension", "Refroidissement cryogénique"],
        "role": "Éclairage spécialisé et applications cryogéniques de niche.",
    },
    11: {
        "occurrence": "Sel gemme (halite, NaCl) et eau de mer (océans : 1,1% de Na). Très abondant - 6ᵉ élément de la croûte.",
        "specificity": "Métal mou, jaune-argenté, qui flotte sur l'eau en explosant. Sa flamme jaune intense (raie D à 589 nm) signe sa présence.",
        "uses": ["Sel de table et conservation alimentaire", "Chlore industriel (électrolyse)", "Lampes à vapeur de sodium", "Caloporteur en réacteur rapide"],
        "role": "Élément vital pour la transmission nerveuse et l'équilibre osmotique.",
    },
    12: {
        "occurrence": "8ᵉ élément le plus abondant. Dolomite, magnésite, eau de mer (3ᵉ ion dissous après Na et Cl).",
        "specificity": "Brûle avec une flamme blanche aveuglante (>3000 °C) - utilisé historiquement dans les flashs photographiques.",
        "uses": ["Alliages aéronautiques légers", "Roues de vélo, ordinateurs portables", "Feux d'artifice et fusées éclairantes", "Antiacides (lait de magnésie)"],
        "role": "Cœur de la chlorophylle (photosynthèse) ; cofacteur de centaines d'enzymes humaines.",
    },
    13: {
        "occurrence": "3ᵉ élément de la croûte terrestre (8%). Extrait de la bauxite (Guinée, Australie, Brésil) par procédé Bayer + Hall-Héroult.",
        "specificity": "Métal le plus utilisé après le fer. Couche d'alumine passivante le protège de la corrosion. Production très énergivore (15 kWh/kg).",
        "uses": ["Emballages (canettes, papier alu)", "Châssis automobiles et aéronautiques", "Câbles haute tension", "Construction (menuiseries)"],
        "role": "Métal léger universel - équilibre légèreté/résistance/recyclabilité unique.",
    },
    14: {
        "occurrence": "2ᵉ élément de la croûte (28%). Quartz, sable, silicates de toutes sortes - feldspaths, micas, argiles.",
        "specificity": "Semi-conducteur dont les propriétés électroniques peuvent être finement contrôlées par dopage (P, B). Base de toute l'électronique moderne.",
        "uses": ["Microprocesseurs et mémoires (wafer de silicium)", "Cellules photovoltaïques", "Verre et béton", "Silicones (joints, lubrifiants)"],
        "role": "Substrat de la révolution informatique et de la transition solaire.",
    },
    15: {
        "occurrence": "Apatites (phosphates de calcium) - Maroc (75% des réserves mondiales), Chine, États-Unis. Présent dans les os et l'ADN.",
        "specificity": "Plusieurs allotropes : blanc (toxique, pyrophorique), rouge (stable), noir (semi-conducteur). Le blanc brille dans l'obscurité.",
        "uses": ["Engrais (60% du tonnage)", "Allumettes", "Détergents (phosphates)", "Munitions et fumigènes (P blanc)"],
        "role": "Constituant essentiel de l'ADN, ATP et des os - ressource agricole stratégique non substituable.",
    },
    16: {
        "occurrence": "Volcans, dépôts évaporitiques (Sicile, Texas, Pologne). Sous-produit du raffinage pétrolier (désulfuration).",
        "specificity": "Allotropes multiples (S₈ cyclique, S₂, polymères). Brûle avec flamme bleue caractéristique en émettant SO₂.",
        "uses": ["Acide sulfurique H₂SO₄ (produit chimique n°1 mondial)", "Vulcanisation du caoutchouc", "Pesticides", "Médicaments (sulfamides)"],
        "role": "Présent dans certains acides aminés (cystéine, méthionine) - essentiel aux protéines.",
    },
    17: {
        "occurrence": "Eau de mer (1,9% en Cl⁻), gisements de sel gemme. Produit par électrolyse de la saumure (procédé chlore-soude).",
        "specificity": "Gaz jaune-vert toxique, à l'odeur suffocante. Utilisé comme arme chimique en 1915 (Ypres). Très oxydant.",
        "uses": ["Désinfection de l'eau potable et des piscines", "PVC (polychlorure de vinyle)", "Solvants industriels", "Blanchiment du papier"],
        "role": "Maintien de l'équilibre hydro-électrolytique ; pilier de la chimie industrielle (PVC, médicaments).",
    },
    18: {
        "occurrence": "0,93% de l'atmosphère - 3ᵉ gaz le plus abondant après N₂ et O₂. Produit par fractionnement de l'air liquide.",
        "specificity": "Totalement inerte chimiquement. Le seul composé connu (HArF) n'a été synthétisé qu'en 2000 à très basse température.",
        "uses": ["Atmosphère inerte (soudure, ampoules incandescentes anciennes)", "Lasers et plasmas", "Vitrages isolants", "Conservation de manuscrits"],
        "role": "Bouclier inerte pour les procédés sensibles à l'oxygène.",
    },
    19: {
        "occurrence": "Sels de potasse (KCl) - Canada (Saskatchewan), Russie, Biélorussie. 7ᵉ élément de la croûte (2,1%).",
        "specificity": "Plus réactif que le sodium ; sa flamme est violet pâle. ⁴⁰K naturellement radioactif (1,3 milliard d'années), source majeure de chaleur interne terrestre.",
        "uses": ["Engrais (95% de l'usage)", "Verre, savons", "Poudre noire (KNO₃)", "Médecine (régulation cardiaque)"],
        "role": "Cation intracellulaire majeur - indispensable à la pompe Na⁺/K⁺ et au potentiel d'action.",
    },
    20: {
        "occurrence": "5ᵉ élément de la croûte. Calcaire, marbre, gypse, craie, coquillages, ossements.",
        "specificity": "Métal réducteur ; ses sels sont à la base de l'industrie cimentière. Hydroxyde Ca(OH)₂ (chaux) connu depuis l'Antiquité.",
        "uses": ["Ciment et béton (CaO)", "Sidérurgie (déphosphoration)", "Suppléments alimentaires", "Stuc et plâtre"],
        "role": "Constituant des os et dents ; second messager cellulaire universel.",
    },
    21: {
        "occurrence": "Très dispersé (peu de gisements concentrés). Sous-produit de l'extraction du tungstène et de l'uranium.",
        "specificity": "Premier des métaux de transition. Densité faible (3 g/cm³) pour un métal de transition.",
        "uses": ["Alliages aérospatiaux (Al-Sc, ultraléger)", "Lampes halogènes haute intensité", "Crosses de baseball, vélos de course"],
        "role": "Alliage de pointe - applications aérospatiales et sportives haut de gamme.",
    },
    22: {
        "occurrence": "9ᵉ élément de la croûte. Rutile (TiO₂), ilménite. Extraction concentrée en Australie, Chine, Afrique du Sud.",
        "specificity": "Rapport résistance/poids exceptionnel ; biocompatible (n'est pas rejeté par l'organisme). Très résistant à la corrosion marine.",
        "uses": ["Implants médicaux (hanches, dents)", "Aéronautique militaire (SR-71, F-22)", "Pigment blanc TiO₂ (peintures, dentifrice, crème solaire)", "Coque de sous-marins"],
        "role": "Métal stratégique de la haute performance - médical, militaire, aérospatial.",
    },
    23: {
        "occurrence": "Magnétite, vanadinite. Production dominée par la Chine, la Russie et l'Afrique du Sud.",
        "specificity": "Multivalent (états +2 à +5), donnant des composés très colorés (bleu, vert, jaune, orange). Pentoxyde V₂O₅ catalyseur clé.",
        "uses": ["Aciers à outils et ressorts (alliage V)", "Batteries vanadium redox (stockage stationnaire)", "Catalyse industrielle (synthèse H₂SO₄)"],
        "role": "Présent dans certaines enzymes marines ; catalyseur industriel essentiel.",
    },
    24: {
        "occurrence": "Chromite (FeCr₂O₄) - Afrique du Sud, Kazakhstan, Inde, Turquie.",
        "specificity": "Métal très dur, brillant, hautement résistant à la corrosion. Donne des composés très colorés (d'où son nom, du grec « chrôma » = couleur).",
        "uses": ["Acier inoxydable (>10% Cr)", "Chromage décoratif et anti-corrosion", "Pigments (vert, jaune, orange)", "Tannage du cuir"],
        "role": "Garde-fou de la corrosion industrielle ; oligo-élément (Cr³⁺ controversé).",
    },
    25: {
        "occurrence": "Pyrolusite (MnO₂), rhodochrosite. Nodules polymétalliques sous-marins en grandes quantités.",
        "specificity": "7 états d'oxydation accessibles (de −3 à +7), record du tableau périodique. Permanganate KMnO₄ violet intense.",
        "uses": ["Acier (additif désoxydant)", "Piles alcalines (MnO₂ cathode)", "Alliage d'aluminium des canettes", "Désinfectant (KMnO₄)"],
        "role": "Cofacteur d'enzymes antioxydantes (SOD) ; pilier de la sidérurgie.",
    },
    26: {
        "occurrence": "4ᵉ élément de la croûte ; cœur métallique de la Terre. Hématite, magnétite, taconite. Australie et Brésil dominent.",
        "specificity": "Métal le plus utilisé au monde. Ferromagnétique. Pic de stabilité nucléaire (élément le plus stable - point final de la nucléosynthèse stellaire).",
        "uses": ["Acier (structures, automobiles, machines - 98% du tonnage métal mondial)", "Aimants", "Catalyse (Haber-Bosch)", "Hémoglobine"],
        "role": "Transporte l'oxygène dans le sang (hémoglobine) ; fondation de toute la civilisation industrielle.",
    },
    27: {
        "occurrence": "Sous-produit de l'extraction du cuivre et du nickel (RDC produit 70% du cobalt mondial).",
        "specificity": "Ferromagnétique avec point de Curie élevé (1115 °C). Pigment bleu cobalt connu depuis l'Antiquité.",
        "uses": ["Batteries lithium-ion (cathodes NMC, NCA)", "Superalliages aéronautiques", "Pigments bleus", "Aimants haute température (Alnico)"],
        "role": "Vitamine B12 (cobalamine) - seul élément à rôle biologique pour la division cellulaire ; ressource géopolitique sensible (cobalt « éthique »).",
    },
    28: {
        "occurrence": "Pentlandite, garniérite. Produit majoritairement en Indonésie, Philippines, Russie, Nouvelle-Calédonie.",
        "specificity": "Ferromagnétique. Très résistant à la corrosion. Existence dans le noyau terrestre conjointement avec le fer.",
        "uses": ["Acier inoxydable (18/8 = 18% Cr, 8% Ni)", "Batteries Ni-MH, Ni-Cd", "Catalyseur d'hydrogénation (margarines)", "Monnaies"],
        "role": "Métal de transition pivot pour la corrosion et la catalyse industrielle.",
    },
    29: {
        "occurrence": "Cuprite, malachite, chalcopyrite. Chili (Chuquicamata), Pérou, RDC, Chine.",
        "specificity": "Excellent conducteur électrique (second après l'argent), excellent conducteur thermique. Antibactérien naturel.",
        "uses": ["Câbles électriques et bobinages", "Plomberie, toitures", "Pièces de monnaie", "Bronze (Cu+Sn) et laiton (Cu+Zn)"],
        "role": "Cofacteur d'enzymes (cytochrome c oxydase, SOD) ; colonne vertébrale de la transition électrique.",
    },
    30: {
        "occurrence": "Sphalérite (ZnS). Chine, Pérou, Australie. Très recyclable (≈30% production secondaire).",
        "specificity": "Métal blanc bleuté qui se passive en surface (carbonate basique). Donne une flamme bleu-vert.",
        "uses": ["Galvanisation anti-rouille de l'acier (50%)", "Laiton (Cu-Zn)", "Piles zinc-carbone", "Suppléments alimentaires, crèmes solaires (ZnO)"],
        "role": "Cofacteur de 300+ enzymes (anhydrase carbonique, ADN polymérases) ; protection anticorrosion industrielle.",
    },
    31: {
        "occurrence": "Sous-produit du raffinage de l'aluminium et du zinc. Pas de minerai propre concentré.",
        "specificity": "Fond dans la main (29,8 °C). Forme liquide-solide étendue : utilisé comme thermomètre cryogénique.",
        "uses": ["Semi-conducteurs LED (GaN bleu/blanc - Nobel 2014)", "Cellules solaires haute efficacité (GaAs)", "Diodes laser", "Thermomètres médicaux (remplaçant le mercure)"],
        "role": "Pilier de l'éclairage LED moderne ; sans GaN, pas de smartphones modernes.",
    },
    32: {
        "occurrence": "Sous-produit de l'extraction du zinc et du charbon (cendres). Chine principal producteur.",
        "specificity": "Métalloïde semi-conducteur. Prédit par Mendeleïev (« eka-silicium ») 16 ans avant sa découverte - triomphe du tableau périodique.",
        "uses": ["Fibre optique (cœur SiO₂-GeO₂)", "Lentilles infrarouges (caméras thermiques)", "Catalyseurs de polymérisation (PET)", "Détecteurs gamma haute résolution"],
        "role": "Composant clé des télécommunications par fibre optique et de l'optique infrarouge.",
    },
    33: {
        "occurrence": "Arsénopyrite, réalgar, orpiment. Sous-produit de l'extraction d'or et de cuivre.",
        "specificity": "Famille des « poisons des rois » - utilisé en assassinat (indétectable jusqu'au test de Marsh, 1836). Cancérigène environnemental majeur.",
        "uses": ["Semi-conducteurs (GaAs)", "Pesticides historiques", "Traitement du bois (CCA, désormais restreint)", "Médicament (leucémie aiguë promyélocytaire - As₂O₃)"],
        "role": "Histoire toxicologique et criminologique ; usage médical paradoxal en oncologie.",
    },
    34: {
        "occurrence": "Sous-produit du raffinage du cuivre. Chili et Japon principaux producteurs.",
        "specificity": "Photoconducteur - sa conductivité augmente sous lumière. Cette propriété a été utilisée dans les photocopieurs et exposemètres.",
        "uses": ["Verres et émaux (rouge sélénium)", "Cellules photoélectriques historiques", "Antipelliculaires (sulfure de sélénium)", "Suppléments antioxydants"],
        "role": "Oligo-élément essentiel (glutathion peroxydase) - antioxydant central.",
    },
    35: {
        "occurrence": "Sels solubles dans l'eau de mer et les saumures (Israël/Mer Morte, États-Unis, Chine).",
        "specificity": "Seul non-métal liquide à température ambiante (avec le mercure pour les métaux). Brun-rouge volatil au pouvoir lacrymogène intense.",
        "uses": ["Retardateurs de flamme (textiles, électronique)", "Bromure d'argent (films photographiques)", "Désinfection des piscines", "Médicaments (sédatifs anciens)"],
        "role": "Présent dans certaines hormones marines ; chimie industrielle des plastiques ignifuges.",
    },
    36: {
        "occurrence": "Atmosphère terrestre à 1,1 ppm. Produit par fractionnement de l'air.",
        "specificity": "Un de ses isotopes (⁸⁶Kr) servait à définir le mètre (1960-1983) avant la définition par la vitesse de la lumière.",
        "uses": ["Lampes flash haute intensité (photographie)", "Lasers KrF (lithographie UV des microprocesseurs)", "Vitrages isolants (entre les vitres)"],
        "role": "Niche de l'optique et de la lithographie semi-conducteurs.",
    },
    37: {
        "occurrence": "Lépidolite, polluxite. Sous-produit du lithium.",
        "specificity": "S'enflamme spontanément à l'air. ⁸⁷Rb radioactif (49 milliards d'années) - utilisé en datation géologique Rb-Sr.",
        "uses": ["Horloges atomiques (étalon de fréquence)", "Photomultiplicateurs", "Verres spéciaux", "Datation géochronologique"],
        "role": "Étalons de précision pour la métrologie du temps.",
    },
    38: {
        "occurrence": "Célestine, strontianite. Espagne, Chine, Mexique.",
        "specificity": "Flamme rouge cramoisi caractéristique - utilisée dans les feux d'artifice. ⁹⁰Sr (radioactif, retombées nucléaires) imite le calcium dans les os.",
        "uses": ["Feux d'artifice et fusées éclairantes rouges", "Verres céramiques", "Aimants ferrite (SrFe₁₂O₁₉)", "Médecine nucléaire (⁸⁹Sr antalgique)"],
        "role": "Marqueur environnemental des essais nucléaires ; pyrotechnie.",
    },
    39: {
        "occurrence": "Souvent associé aux terres rares (xénotime, monazite). Chine produit ~70%.",
        "specificity": "Premier élément classé « terre rare » (mais en réalité pas si rare - plus abondant que l'argent). Découvert près du village d'Ytterby en Suède (4 éléments y portent son nom).",
        "uses": ["YAG (laser, prothèse dentaire)", "Phosphores rouges des écrans (Y₂O₃:Eu)", "Supraconducteurs haute température (YBaCuO)", "Alliages aérospatiaux"],
        "role": "Indispensable aux dispositifs laser et aux écrans modernes.",
    },
    40: {
        "occurrence": "Zircon (ZrSiO₄), badeleyite. Australie, Afrique du Sud.",
        "specificity": "Transparent aux neutrons thermiques - usage nucléaire critique. Très résistant à la corrosion (passivation par ZrO₂).",
        "uses": ["Gaines de combustible nucléaire (alliage Zircaloy)", "Bijouterie (zircon, cubic zirconia comme faux diamant)", "Implants médicaux", "Céramiques techniques"],
        "role": "Métal stratégique du nucléaire civil - sans Zircaloy, pas de réacteur à eau pressurisée.",
    },
    41: {
        "occurrence": "Columbite-tantalite (coltan). Brésil et Canada principaux producteurs.",
        "specificity": "Devient supraconducteur à 9,3 K (le plus élevé des éléments purs). Très résistant et bio-inerte.",
        "uses": ["Aciers HSLA (gazoducs, automobile)", "Aimants supraconducteurs (IRM, accélérateurs)", "Implants médicaux", "Bijouterie hypoallergénique"],
        "role": "Acier de haute performance et supraconductivité de pointe (IRM, LHC, ITER).",
    },
    42: {
        "occurrence": "Molybdénite (MoS₂). Sous-produit du cuivre. États-Unis, Chine, Chili.",
        "specificity": "Point de fusion très élevé (2623 °C). Très bon catalyseur. Essentiel à la nitrogénase bactérienne (fixation N₂).",
        "uses": ["Aciers à outils et inox haute température", "Catalyse (désulfuration des carburants)", "Lubrifiants (MoS₂ sec)", "Filaments de four"],
        "role": "Cofacteur enzymatique (nitrogénase, xanthine oxydase) ; métallurgie haute température.",
    },
    43: {
        "occurrence": "Premier élément artificiel (1937). Trace dans les minerais d'uranium par fission spontanée. Tous ses isotopes sont radioactifs.",
        "specificity": "« Trou » du tableau périodique enfin comblé. ⁹⁹ᵐTc, émetteur gamma idéal pour imagerie (demi-vie 6h).",
        "uses": ["Imagerie médicale par scintigraphie (⁹⁹ᵐTc - 30 millions d'examens/an mondial)", "Anti-corrosion (films de pertechnétate)"],
        "role": "Outil médical n°1 de l'imagerie nucléaire fonctionnelle.",
    },
    44: {
        "occurrence": "Sous-produit du raffinage du nickel et du platine. Russie, Afrique du Sud.",
        "specificity": "Catalyseur exceptionnel pour les réactions organiques. Métal du groupe du platine, dur et cassant.",
        "uses": ["Catalyse fine (Nobel 2010 - couplages organiques)", "Disques durs (couches magnétiques)", "Bijouterie (alliage avec Pt)", "Thérapie anticancéreuse (cisplatine analogues)"],
        "role": "Catalyseur central de la chimie organique moderne.",
    },
    45: {
        "occurrence": "Sous-produit ultra-rare du nickel-cuivre-platine. Afrique du Sud (80%), Russie.",
        "specificity": "Métal le plus cher du monde (~13 000 €/oz, plus que l'or). Reflectance optique exceptionnelle.",
        "uses": ["Pots catalytiques automobiles (oxydation NOx)", "Bijoux et miroirs", "Thermocouples haute température", "Catalyse fine"],
        "role": "Indispensable à la réduction des émissions automobiles.",
    },
    46: {
        "occurrence": "Russie, Afrique du Sud, Canada. Métal du groupe du platine.",
        "specificity": "Absorbe jusqu'à 900 fois son volume en hydrogène - propriété unique. Catalyseur omniprésent.",
        "uses": ["Pots catalytiques (essence)", "Bijouterie (or blanc)", "Couplage croisé en chimie fine", "Stockage d'hydrogène (recherche)"],
        "role": "Catalyseur le plus polyvalent ; clé des moteurs essence dépolluants.",
    },
    47: {
        "occurrence": "Argentite, sous-produit du plomb-zinc-cuivre. Mexique, Pérou, Chine.",
        "specificity": "Meilleur conducteur électrique et thermique de tous les métaux. Antimicrobien à très faible dose.",
        "uses": ["Bijouterie et argenterie", "Contacts électriques de haute fiabilité", "Photographie argentique (AgBr, AgCl)", "Cellules solaires (pâte d'Ag)"],
        "role": "Métal monétaire historique ; biocide ancestral, conducteur d'élite.",
    },
    48: {
        "occurrence": "Sous-produit du zinc (greenockite). Toxique et bioaccumulable.",
        "specificity": "Couleurs jaune-orange-rouge intenses des pigments cadmium. Bioaccumulation rénale dramatique (maladie d'itai-itai au Japon).",
        "uses": ["Pigments jaunes/rouges (peinture)", "Batteries Ni-Cd (en déclin)", "Cellules solaires CdTe (couches minces)", "Barres de contrôle nucléaire"],
        "role": "Métal toxique en sortie progressive des usages ; valable en photovoltaïque CdTe.",
    },
    49: {
        "occurrence": "Sous-produit du zinc et du plomb. Chine, Corée, Japon.",
        "specificity": "Métal mou qui « crie » en se déformant (cri caractéristique des cristaux). Soudures basse température.",
        "uses": ["ITO (oxyde d'indium-étain) - couche transparente conductrice des écrans tactiles et OLED", "Soudures sans plomb", "Roulements aéronautiques"],
        "role": "Sans indium, pas d'écrans tactiles ni de cellules photovoltaïques modernes - ressource critique.",
    },
    50: {
        "occurrence": "Cassitérite (SnO₂). Indonésie, Chine, Pérou, Bolivie. Métal connu depuis l'âge du bronze.",
        "specificity": "Possède deux allotropes (étain blanc β / étain gris α) - la « peste de l'étain » ronge les objets en hiver (transformation à 13 °C).",
        "uses": ["Soudures électroniques (Sn-Ag-Cu sans plomb)", "Fer-blanc (boîtes de conserve)", "Bronze (Cu-Sn) - premier alliage de l'humanité", "Verre flotté (procédé Pilkington)"],
        "role": "Métal stratégique de l'électronique grand public (soudures).",
    },
    51: {
        "occurrence": "Stibine (Sb₂S₃). Chine domine (80% production mondiale).",
        "specificity": "Métalloïde semi-conducteur. Khol antique des Égyptiennes (Sb₂S₃ noir). Se dilate en se solidifiant comme l'eau et le bismuth.",
        "uses": ["Retardateurs de flamme (textiles, plastiques)", "Plomb d'accumulateurs (durcissement)", "Semi-conducteurs InSb (infrarouge)", "Munitions"],
        "role": "Sécurité incendie industrielle ; histoire cosmétique millénaire.",
    },
    52: {
        "occurrence": "Sous-produit du raffinage cuivre/plomb. Chili, Pérou, Suède.",
        "specificity": "Odeur ail caractéristique de ses composés organiques (ingestion de Te → mauvaise haleine durant des semaines).",
        "uses": ["Cellules photovoltaïques CdTe (procédé First Solar)", "Verres optiques infrarouges", "Aciers et alliages amélioration usinage", "Vulcanisation"],
        "role": "Pilier émergent du photovoltaïque couches minces à bas coût.",
    },
    53: {
        "occurrence": "Saumures iodées (Chili, Japon). Algues marines (laminaires).",
        "specificity": "Seul halogène solide à température ambiante (cristaux noir-violet). Se sublime en vapeur violette.",
        "uses": ["Antiseptique (Bétadine, teinture d'iode)", "Sel iodé (prévention du goitre)", "Médicaments (amiodarone)", "Pellicules photo, plaques offset"],
        "role": "Indispensable à la thyroïde (synthèse de T3/T4) - carence = goitre.",
    },
    54: {
        "occurrence": "Atmosphère à 0,09 ppm seulement. Fractionnement de l'air.",
        "specificity": "Premier gaz noble dont on a synthétisé un composé (XeF₂, 1962) - révolution dans la conception de la liaison chimique.",
        "uses": ["Phares automobiles à décharge (lampes xénon HID)", "Anesthésique neuroprotecteur", "Propulseur de satellites (moteurs ioniques)", "Détection de matière noire (XENON, LZ)"],
        "role": "Anesthésie de luxe et propulsion spatiale d'avant-garde.",
    },
    55: {
        "occurrence": "Pollucite (rare). Canada produit ~80%.",
        "specificity": "Métal le plus mou et le plus réactif (avec le francium). Fond à 28,5 °C (peut fondre dans la main). Étalon de la seconde (¹³³Cs).",
        "uses": ["Horloges atomiques (définition de la seconde depuis 1967)", "Forage pétrolier (boues denses au formiate de césium)", "Photovoltaïque pérovskite (recherche)"],
        "role": "Étalon mondial du temps - toute la métrologie en dépend.",
    },
    56: {
        "occurrence": "Barytine (BaSO₄), withérite. Chine, Inde, États-Unis.",
        "specificity": "Métal mou jaune-argenté. Sels insolubles (BaSO₄) opaques aux rayons X.",
        "uses": ["Repas baryté (radiographie du tube digestif)", "Boue de forage pétrolier (BaSO₄ très dense)", "Feux d'artifice verts", "Aimants ferrites"],
        "role": "Outil radiologique gastro-intestinal incontournable.",
    },
    57: {
        "occurrence": "Bastnäsite, monazite. Chine, États-Unis, Australie. Premier des lanthanides.",
        "specificity": "« Pierre de touche » des terres rares. Très électropositif. Donne ses 3 électrons facilement.",
        "uses": ["Verres optiques à haut indice (objectifs photo)", "Catalyseurs de craquage pétrolier (FCC)", "Briquets pyrophoriques (Mischmetal)"],
        "role": "Optique haut de gamme et catalyse pétrolière.",
    },
    58: {
        "occurrence": "Le plus abondant des lanthanides (5ᵉ rare earth en abondance crustale). Bastnäsite, monazite.",
        "specificity": "Deux états +3 et +4 (rare chez les lanthanides). Oxyde CeO₂ catalyseur exceptionnel.",
        "uses": ["Catalyseurs automobiles (CeO₂ stockage d'O₂)", "Polissage du verre (poudre rouge)", "Verres anti-UV", "Pierres à briquet"],
        "role": "Composant central des pots catalytiques modernes.",
    },
    59: {
        "occurrence": "Monazite, bastnäsite. Toujours co-extrait des autres terres rares.",
        "specificity": "Verts intenses des verres et émaux. Légèrement paramagnétique.",
        "uses": ["Aimants permanents (didymium = Pr+Nd)", "Verres de soudage (filtres oculaires)", "Allumeurs de briquet (pyrophorique)", "Lasers"],
        "role": "Magnétisme haute performance avec le néodyme.",
    },
    60: {
        "occurrence": "Bastnäsite, monazite. Production dominée par la Chine.",
        "specificity": "Donne les aimants permanents les plus puissants connus (Nd₂Fe₁₄B). Mince couche peut soulever 1000× son poids.",
        "uses": ["Aimants Nd-Fe-B (éoliennes, voitures électriques, disques durs)", "Lasers Nd:YAG (médecine, industrie, militaire)", "Verres colorés"],
        "role": "Cœur des moteurs électriques modernes et des éoliennes - ressource critique.",
    },
    61: {
        "occurrence": "Aucun isotope stable. Trace dans la pechblende ; produit par fission. Le seul lanthanide artificiel.",
        "specificity": "Demi-vie maximale : ¹⁴⁵Pm, 17,7 ans. Émetteur β.",
        "uses": ["Peintures luminescentes (montres, instruments) - remplaçant du radium", "Batteries nucléaires bêta-voltaïques", "Mesure d'épaisseur de couches"],
        "role": "Sources radioluminescentes de longue durée.",
    },
    62: {
        "occurrence": "Monazite, bastnäsite. Co-produit des terres rares.",
        "specificity": "Forme avec le cobalt l'aimant SmCo₅ - résistant à très haute température. Capture de neutrons élevée (¹⁴⁹Sm).",
        "uses": ["Aimants SmCo (turbines, capteurs haute température, militaire)", "Barres de contrôle de réacteurs", "Datation Sm-Nd en géologie"],
        "role": "Aimants résistant à la chaleur - applications militaires et aérospatiales.",
    },
    63: {
        "occurrence": "Bastnäsite, monazite. L'un des lanthanides les plus rares en abondance.",
        "specificity": "Couleur unique de ses ions (Eu²⁺ bleu, Eu³⁺ rouge). Phosphore essentiel des écrans.",
        "uses": ["Phosphore rouge des écrans TV/LED/OLED", "Sécurité des billets en euros (encres luminescentes UV)", "Lampes fluorescentes (raie rouge)"],
        "role": "Signature visuelle des écrans modernes - sans Eu, pas de rouge cathodique ni LED.",
    },
    64: {
        "occurrence": "Gadolinite, bastnäsite. Co-produit des terres rares.",
        "specificity": "Section efficace de capture neutronique la plus élevée de tous les éléments (point Ferromagnétique à 19 °C).",
        "uses": ["Agents de contraste IRM (chélates de Gd³⁺)", "Barres de contrôle nucléaires", "Phosphores verts", "Disques magnéto-optiques"],
        "role": "Sans Gd, pas d'IRM avec contraste - outil de diagnostic médical clé.",
    },
    65: {
        "occurrence": "Co-produit des terres rares.",
        "specificity": "Fluorescence verte caractéristique sous UV. Forte magnétostriction (changement de forme sous champ magnétique).",
        "uses": ["Phosphores verts (tubes fluorescents, lampes LED)", "Actionneurs magnétostrictifs (sonars)", "Stockage magnéto-optique"],
        "role": "Composant fluorescent et acoustique sous-marin.",
    },
    66: {
        "occurrence": "Co-extrait des terres rares.",
        "specificity": "Magnétostriction et capacité calorifique magnétique extrêmes (utilisé en réfrigération magnétique).",
        "uses": ["Aimants haute température (additif à Nd-Fe-B pour véhicules électriques)", "Sonars (Terfenol-D)", "Lasers", "Réfrigération magnétique (recherche)"],
        "role": "Améliore les aimants des moteurs électriques en endurance thermique.",
    },
    67: {
        "occurrence": "Gadolinite, monazite (très dispersé).",
        "specificity": "Plus fort moment magnétique de tous les éléments. Production très minoritaire.",
        "uses": ["Concentrateurs de champ magnétique (IRM haute résolution, recherche)", "Lasers chirurgicaux Ho:YAG (urologie, prostate)", "Spectroscopie"],
        "role": "Médecine laser de précision et IRM avancée.",
    },
    68: {
        "occurrence": "Co-extrait des terres rares.",
        "specificity": "Absorption pic à 1550 nm - longueur d'onde des télécommunications optiques.",
        "uses": ["Amplificateurs optiques EDFA (Erbium-Doped Fiber Amplifier - Internet mondial)", "Lasers Er:YAG (dentisterie)", "Verres rosés", "Lunettes de soudure"],
        "role": "Sans Er, pas d'Internet à fibre optique transocéanique.",
    },
    69: {
        "occurrence": "Très rare - le moins abondant des lanthanides non radioactifs.",
        "specificity": "Émission de rayons X par bombardement électronique. Demi-vie courte de ¹⁷⁰Tm (128 j).",
        "uses": ["Sources portables de rayons X (radiographie médicale d'urgence)", "Lasers (chirurgie)", "Mesure de dose radiologique"],
        "role": "Radiologie portable, applications de niche.",
    },
    70: {
        "occurrence": "Monazite, gadolinite.",
        "specificity": "Très haute capture neutronique. Métal mou, facile à fondre.",
        "uses": ["Dopants des aciers inoxydables", "Lasers fibre (Yb:YAG industrielle, découpe métal)", "Horloges atomiques optiques de pointe"],
        "role": "Métrologie temps de nouvelle génération (horloges optiques).",
    },
    71: {
        "occurrence": "Le plus rare et le plus cher des lanthanides.",
        "specificity": "Le plus dur et le plus dense des lanthanides. Datation U-Pb-Lu en géologie.",
        "uses": ["Catalyse de craquage pétrolier", "Datation géologique", "Détection PET (¹⁷⁷Lu en thérapie ciblée des tumeurs neuroendocrines)"],
        "role": "Médecine nucléaire ciblée des cancers (lutathérapie).",
    },
    72: {
        "occurrence": "Toujours associé au zirconium (90% similaire chimiquement). Australie principal producteur.",
        "specificity": "Antagoniste du zircon : forte capture neutronique, à l'inverse de Zr utilisé pour son transparence.",
        "uses": ["Barres de contrôle des réacteurs nucléaires (sous-marins militaires)", "Superalliages haute température", "Microprocesseurs (HfO₂ remplace SiO₂ comme diélectrique)"],
        "role": "Sans HfO₂, pas de transistors sub-45 nm - clé de l'électronique moderne.",
    },
    73: {
        "occurrence": "Coltan (avec Nb). Produit dans les zones de conflit (RDC). Australie, Brésil aussi.",
        "specificity": "Bio-inerte ; résiste à presque tous les acides. Densité élevée.",
        "uses": ["Condensateurs miniatures (smartphones, électronique)", "Implants chirurgicaux", "Outils de coupe (carbure de tantale)"],
        "role": "Sans condensateurs Ta, pas de smartphone fin - minéral controversé géopolitiquement.",
    },
    74: {
        "occurrence": "Wolframite, scheelite. Chine produit ~80%.",
        "specificity": "Point de fusion le plus élevé de tous les métaux (3422 °C). Très dense (19,3 g/cm³, proche de l'or).",
        "uses": ["Filaments d'ampoules incandescentes (historique)", "Outils de coupe (carbure de tungstène)", "Munitions perforantes", "Lestes de fléchettes et clubs de golf"],
        "role": "Métal incontournable des températures extrêmes et de l'usinage de précision.",
    },
    75: {
        "occurrence": "Le plus rare des éléments naturels stables (~0,7 ppb dans la croûte). Sous-produit Mo-Cu.",
        "specificity": "3ᵉ point de fusion le plus élevé (3186 °C). Métal le plus dense après Os, Ir, Pt.",
        "uses": ["Superalliages aéronautiques (aubes de turbine haute température)", "Catalyseurs de reformage essence (Pt-Re)", "Thermocouples haute température"],
        "role": "Métal exotique des moteurs d'avion à réaction modernes.",
    },
    76: {
        "occurrence": "Sous-produit du raffinage du platine et du nickel.",
        "specificity": "Élément le plus dense connu (22,59 g/cm³). Cristaux d'OsO₄ extrêmement toxiques et volatils.",
        "uses": ["Pointes de stylos plumes haut de gamme", "Coloration histologique (OsO₄ pour microscopie électronique)", "Catalyse fine"],
        "role": "Densité record - usages très spécialisés.",
    },
    77: {
        "occurrence": "Métal le plus rare de la croûte. Pic de concentration à la limite K-Pg (extinction des dinosaures, 66 Ma) - signature de l'astéroïde de Chicxulub.",
        "specificity": "Le plus résistant à la corrosion de tous les métaux. Étalon historique du kilogramme et du mètre (Pt-Ir).",
        "uses": ["Étalons et instruments scientifiques", "Bougies haute performance moteurs", "Creusets pour cristaux", "Implants médicaux haut de gamme"],
        "role": "Témoin géologique de l'extinction massive ; étalon de précision.",
    },
    78: {
        "occurrence": "Sibérie, Afrique du Sud. Souvent associé aux gisements de chromite et nickel.",
        "specificity": "Très inerte chimiquement - d'où son utilisation en bijouterie et catalyse. Catalyseur le plus polyvalent.",
        "uses": ["Pots catalytiques automobiles (diesel)", "Bijouterie luxe", "Médicaments (cisplatine, carboplatine - anticancéreux)", "Catalyse industrielle"],
        "role": "Pilier de la chimiothérapie au platine (sels coordonnés) et de la dépollution automobile.",
    },
    79: {
        "occurrence": "Filons hydrothermaux. Afrique du Sud (en déclin), Chine, Australie, Russie, USA.",
        "specificity": "Inerte (« noble » par excellence), très ductile et malléable (1 g s'étire en fil de 2,4 km). Étalon monétaire ancestral.",
        "uses": ["Bijouterie (50% de la demande)", "Réserves de valeur et banques centrales", "Électronique haut de gamme (connecteurs)", "Médecine (implants dentaires, traitement arthrite)"],
        "role": "Étalon monétaire universel depuis 5000 ans ; valeur refuge.",
    },
    80: {
        "occurrence": "Cinabre (HgS). Espagne (mine d'Almadén historique), Chine, Pérou.",
        "specificity": "Seul métal liquide à température ambiante. Très toxique (neurotoxique, bioaccumulé en méthylmercure dans les poissons).",
        "uses": ["Thermomètres et baromètres historiques (en sortie progressive)", "Tubes fluorescents", "Amalgames dentaires (en déclin)", "Electrolyse industrielle (chlore-soude)"],
        "role": "Convention de Minamata (2013) : sortie progressive des usages - métal symbolique des pollutions historiques.",
    },
    81: {
        "occurrence": "Sous-produit cuivre/plomb/zinc.",
        "specificity": "Très toxique (« poison de l'empoisonneuse » - Agatha Christie). Inodore, insipide, soluble.",
        "uses": ["Détecteurs infrarouges (Tl-Cs photoémetteur)", "Verres haute densité", "Médecine nucléaire (cardiologie ²⁰¹Tl, en déclin)", "Mort-aux-rats (interdit en Europe)"],
        "role": "Histoire toxicologique et criminelle ; usages techniques limités.",
    },
    82: {
        "occurrence": "Galène (PbS) - connu depuis l'Antiquité. Chine, Australie, USA. Très recyclable.",
        "specificity": "Métal le plus utilisé historiquement. Toxique cumulatif (saturnisme - possible cause du déclin de Rome via plomberie).",
        "uses": ["Batteries plomb-acide (automobile - 80% de l'usage)", "Boucliers anti-radiations", "Munitions (chasse, militaire)", "Soudure (en déclin)"],
        "role": "Cœur des batteries de démarrage automobile ; protection contre rayonnements ionisants.",
    },
    83: {
        "occurrence": "Sous-produit cuivre/plomb. Chine, Mexique, Bolivie.",
        "specificity": "« Métal lourd non toxique » - paradoxe pour un voisin du plomb et du polonium. Demi-vie naturelle de ²⁰⁹Bi mesurée à 2×10¹⁹ ans (techniquement instable, mais effectivement éternel).",
        "uses": ["Pepto-Bismol (anti-ulcère)", "Cosmétiques perlés", "Soudures sans plomb", "Alliages fusibles (extincteurs automatiques)"],
        "role": "Substitut « propre » du plomb en pharmacie et soudure.",
    },
    84: {
        "occurrence": "Trace dans la pechblende (uranium). Découvert par Marie Curie (1898), nommé d'après la Pologne.",
        "specificity": "Hautement radioactif et toxique (1 g vaut 250 000 doses létales humaines). Empoisonnement célèbre d'Alexandre Litvinenko (2006).",
        "uses": ["Sources alpha calibrées (industrie, recherche)", "Antistatique (élimination électricité statique)", "Anciennement : générateurs thermoélectriques sondes spatiales (RTG)"],
        "role": "Marqueur historique de la radioactivité (découverte par les Curie).",
    },
    85: {
        "occurrence": "Élément naturel le plus rare (~25 g existeraient simultanément dans toute la croûte). Trace dans les minerais d'uranium.",
        "specificity": "Tous les isotopes radioactifs ; le plus stable (²¹⁰At) a une demi-vie de 8,1 heures. Probablement métallique (jamais observé en quantité macroscopique).",
        "uses": ["Thérapies alpha ciblées des cancers (recherche oncologique)", "Recherche fondamentale"],
        "role": "Outil expérimental de radiothérapie ciblée du XXIᵉ siècle.",
    },
    86: {
        "occurrence": "Gaz issu de la désintégration de l'uranium dans les sols et roches granitiques. S'accumule dans les caves mal ventilées.",
        "specificity": "Gaz noble radioactif (²²²Rn, demi-vie 3,8 j). 2ᵉ cause de cancer du poumon après le tabac.",
        "uses": ["Curiethérapie (historiquement)", "Datation des eaux souterraines", "Suivi sismique (variations de Rn préfigurent certains séismes)"],
        "role": "Risque sanitaire majeur ; révélateur géologique de l'uranium et des séismes.",
    },
    87: {
        "occurrence": "Trace dans la pechblende (~30 g existeraient sur toute la Terre). Découvert en France (Marguerite Perey, 1939).",
        "specificity": "Le plus rare des éléments naturels (après At). ²²³Fr demi-vie 22 minutes. Métal le plus réactif chimiquement.",
        "uses": ["Recherche fondamentale uniquement (étude des effets relativistes sur les électrons)"],
        "role": "Test des limites de la chimie atomique.",
    },
    88: {
        "occurrence": "Trace dans la pechblende. Découvert par les Curie (1898).",
        "specificity": "Million de fois plus radioactif que l'uranium. Cause les premières montres luminescentes (et empoisonnements ouvriers - « Radium Girls »).",
        "uses": ["Radiothérapie historique (en sortie totale)", "²²³Ra : traitement palliatif des métastases osseuses (Xofigo)", "Recherche"],
        "role": "Symbole tragique des débuts de la radioactivité ; outil oncologique moderne ciblé.",
    },
    89: {
        "occurrence": "Trace dans l'uranium. Demi-vie ²²⁷Ac : 21,8 ans.",
        "specificity": "Donne son nom à toute la série actinide. Émet une faible lueur bleue (rayonnement Cherenkov).",
        "uses": ["Source de neutrons (Ac-Be)", "Thérapie alpha ciblée (²²⁵Ac contre cancers métastatiques - essais cliniques)"],
        "role": "Médecine nucléaire ciblée d'avant-garde.",
    },
    90: {
        "occurrence": "Monazite, thorite. Plus abondant que l'uranium dans la croûte. Inde, Brésil, Australie.",
        "specificity": "Faiblement radioactif (demi-vie ²³²Th : 14 milliards d'années - âge de l'univers). Fertile (transmute en ²³³U fissile).",
        "uses": ["Combustible nucléaire (réacteurs sels fondus - recherche)", "Manchons à incandescence (historique)", "Verres optiques", "Soudage TIG"],
        "role": "Alternative future au cycle uranium - promesse de l'énergie nucléaire au thorium.",
    },
    91: {
        "occurrence": "Trace dans la pechblende. Découvert en 1913 par Fajans et Göhring, isolé par Hahn et Meitner.",
        "specificity": "Un des éléments naturels les plus rares. Demi-vie ²³¹Pa : 32 760 ans.",
        "uses": ["Datation océanographique (sédiments, Pa/Th)", "Recherche fondamentale"],
        "role": "Chronologie des paléoclimats marins.",
    },
    92: {
        "occurrence": "Pechblende, uraninite. Kazakhstan, Canada, Australie produisent ~70%. Plus commun que l'argent.",
        "specificity": "Plus lourd des éléments primordiaux significatifs. ²³⁵U fissile (0,72% du naturel). Premier essai nucléaire en 1945.",
        "uses": ["Combustible des centrales nucléaires (~10% de l'électricité mondiale)", "Armes nucléaires", "Munitions perforantes (uranium appauvri)"],
        "role": "Pilier de l'énergie nucléaire civile et de la dissuasion ; controverses environnementales et géopolitiques majeures.",
    },
    93: {
        "occurrence": "Premier élément transuranien découvert (1940, McMillan & Abelson). Produit en réacteur.",
        "specificity": "Demi-vie ²³⁷Np : 2,1 millions d'années. Brille faiblement par radioluminescence propre.",
        "uses": ["Détecteurs de neutrons", "Source pour la production de ²³⁸Pu (sondes spatiales)"],
        "role": "Marqueur de pollution nucléaire post-1945.",
    },
    94: {
        "occurrence": "Produit en réacteur depuis l'uranium-238 (n,γ). Trace naturelle infime dans l'uraninite.",
        "specificity": "²³⁹Pu fissile et fissile par neutrons rapides - cœur des armes nucléaires modernes et des surgénérateurs. ²³⁸Pu : chaleur intense, sondes Voyager, Cassini, Mars rovers.",
        "uses": ["Combustible MOX (mélange UO₂/PuO₂)", "Armes nucléaires", "Générateurs RTG des sondes spatiales", "Stimulateurs cardiaques (historique)"],
        "role": "Énergie spatiale lointaine et dissuasion nucléaire.",
    },
    95: {
        "occurrence": "Synthétisé en réacteur depuis ²³⁹Pu (1944, Seaborg). Produit en grammes/an.",
        "specificity": "Demi-vie ²⁴¹Am : 432 ans. Forte source alpha et gamma.",
        "uses": ["Détecteurs de fumée domestiques (~0,3 µg par détecteur - un des seuls usages domestiques d'un transuranien)", "Sources d'étalonnage", "Recherche fondamentale"],
        "role": "Sécurité incendie à domicile - élément invisible mais présent partout.",
    },
    96: {
        "occurrence": "Synthétisé par bombardement neutronique du plutonium.",
        "specificity": "Hautement radioactif. ²⁴⁴Cm : 18 ans. Lueur violette intense.",
        "uses": ["Générateurs alpha pour engins spatiaux (rovers martiens - analyse APXS)", "Source de neutrons"],
        "role": "Outil de spectroscopie planétaire (rovers Spirit, Opportunity, Curiosity, Perseverance).",
    },
    97: {
        "occurrence": "Synthétisé en accélérateur (1949, Berkeley) en quantités picogrammes.",
        "specificity": "²⁴⁷Bk : 1380 ans. Très rare et coûteux.",
        "uses": ["Recherche fondamentale - utilisé pour synthétiser le tennesse (Z=117)"],
        "role": "Cible de synthèse des éléments superlourds.",
    },
    98: {
        "occurrence": "Synthétisé en accélérateur (1950, Berkeley).",
        "specificity": "²⁵²Cf : émetteur neutronique exceptionnellement intense (2,3×10¹² n/s/g). Demi-vie 2,6 ans.",
        "uses": ["Source portable de neutrons (logging pétrolier, démarrage de réacteurs nucléaires)", "Radiothérapie de tumeurs profondes", "Détection d'explosifs"],
        "role": "Un des rares transuraniens à usage commercial - source neutronique mobile.",
    },
    99: {
        "occurrence": "Découvert dans les retombées du premier essai thermonucléaire Ivy Mike (1952). Synthèse difficile.",
        "specificity": "Demi-vie ²⁵²Es : 472 jours. Émet sa propre lumière par radioluminescence intense.",
        "uses": ["Recherche fondamentale (cible pour synthétiser le mendélévium Z=101)"],
        "role": "Témoin de l'aube des armes thermonucléaires.",
    },
    100: {
        "occurrence": "Découvert également dans les retombées d'Ivy Mike (1952). Synthèse en accélérateur.",
        "specificity": "Demi-vie maximale ²⁵⁷Fm : 100,5 jours. Dernier élément que l'on sait préparer en quantité pesable.",
        "uses": ["Aucune application pratique - recherche fondamentale"],
        "role": "Frontière entre éléments « lourds traçables » et superlourds invisibles.",
    },
    101: {
        "occurrence": "Synthétisé un atome à la fois (1955, Berkeley) par bombardement d'einsteinium par hélium.",
        "specificity": "Premier élément découvert un atome à la fois. Demi-vie ²⁵⁸Md : 51 jours.",
        "uses": ["Recherche fondamentale"],
        "role": "Hommage à Mendeleïev, créateur du tableau périodique.",
    },
    102: {
        "occurrence": "Synthétisé en accélérateur (1958, Dubna et Berkeley - paternité contestée).",
        "specificity": "Demi-vie ²⁵⁹No : 58 minutes. Dernier actinide à comportement chimique observé.",
        "uses": ["Recherche fondamentale"],
        "role": "Hommage à Alfred Nobel.",
    },
    103: {
        "occurrence": "Synthétisé en 1961 à Berkeley.",
        "specificity": "Dernier des actinides. Demi-vie ²⁶²Lr : 4 heures. Configuration électronique inattendue (7p au lieu de 6d) - relativiste.",
        "uses": ["Recherche fondamentale"],
        "role": "Fermeture de la série actinide ; test des effets relativistes.",
    },
    104: {
        "occurrence": "Synthétisé en laboratoire à Dubna (JINR, 1964) par fusion plutonium-242 + néon-22, confirmé à Berkeley (1969) via californium-249 + carbone-12.",
        "specificity": "Premier transactinide du tableau périodique ; isotope le plus stable ²⁶⁷Rf avec une demi-vie d'environ 1,3 heure, se désintègre par émission alpha et fission spontanée.",
        "uses": ["Aucune application pratique - recherche fondamentale uniquement"],
        "role": "Étude du comportement chimique des transactinides et test des effets relativistes sur la couche 6d.",
    },
    105: {
        "occurrence": "Synthétisé en laboratoire à Dubna (JINR, 1967) et confirmé à Berkeley (1970) par bombardement de cibles d'américium ou de californium avec des ions néon-22 ou azote-15.",
        "specificity": "Transactinide hautement radioactif ; isotope le plus stable ²⁶⁸Db avec une demi-vie d'environ 29 heures, au cœur d'une longue controverse de nommage entre USA et URSS.",
        "uses": ["Aucune application pratique - recherche fondamentale uniquement"],
        "role": "Validation des modèles de chimie aqueuse des éléments superlourds (analogue prédit du tantale).",
    },
    106: {
        "occurrence": "Synthétisé indépendamment en 1974 à Dubna (JINR) et à Berkeley par les réactions ²⁰⁸Pb + ⁵⁴Cr et ²⁴⁹Cf + ¹⁸O.",
        "specificity": "Demi-vie d'environ 14 minutes pour ²⁶⁹Sg ; la synthèse de l'hexacarbonyle Sg(CO)₆ a démontré sa parenté chimique avec le molybdène et le tungstène. Nommé du vivant de Glenn Seaborg.",
        "uses": ["Aucune application pratique - recherche fondamentale uniquement"],
        "role": "Vérification expérimentale de la chimie organométallique des transactinides du groupe 6.",
    },
    107: {
        "occurrence": "Synthétisé en 1981 au GSI de Darmstadt (Allemagne) par fusion froide de bismuth-209 avec des ions chrome-54.",
        "specificity": "Isotope le plus stable ²⁷⁰Bh avec une demi-vie d'environ 1 minute ; se désintègre par émission alpha. Nommé en l'honneur de Niels Bohr en 1997.",
        "uses": ["Aucune application pratique - recherche fondamentale uniquement"],
        "role": "Étude chimique du groupe 7 (analogue lourd du rhénium) via des oxychlorures volatils.",
    },
    108: {
        "occurrence": "Synthétisé en 1984 au GSI de Darmstadt par bombardement de plomb-208 avec des ions fer-58.",
        "specificity": "Isotope ²⁷⁰Hs doublement magique (108 protons, 162 neutrons) avec une demi-vie d'environ 22 secondes, suggérant une stabilité accrue à proximité de l'îlot de stabilité.",
        "uses": ["Aucune application pratique - recherche fondamentale uniquement"],
        "role": "Test expérimental des nombres magiques nucléaires déformés et étude de HsO₄ (analogue volatil de l'osmium).",
    },
    109: {
        "occurrence": "Synthétisé le 29 août 1982 au GSI de Darmstadt par Armbruster et Münzenberg via bombardement de bismuth-209 avec des ions fer-58.",
        "specificity": "Isotope le plus stable ²⁷⁸Mt avec une demi-vie d'environ 7,6 secondes ; nommé en l'honneur de Lise Meitner, codécouvreuse de la fission nucléaire.",
        "uses": ["Aucune application pratique - recherche fondamentale uniquement"],
        "role": "Sondage des propriétés des métaux de transition 6d et exploration de la frontière entre fusion chaude et fusion froide.",
    },
    110: {
        "occurrence": "Synthétisé le 9 novembre 1994 au GSI de Darmstadt par fusion froide de plomb-208 avec des ions nickel-62.",
        "specificity": "Isotope le plus stable ²⁸¹Ds avec une demi-vie d'environ 12,7 secondes ; analogue prédit du platine, baptisé d'après la ville de Darmstadt.",
        "uses": ["Aucune application pratique - recherche fondamentale uniquement"],
        "role": "Sonde des effets relativistes sur les orbitales 6d et étude des éléments du groupe 10.",
    },
    111: {
        "occurrence": "Synthétisé en décembre 1994 au GSI de Darmstadt par bombardement de bismuth-209 avec des ions nickel-64.",
        "specificity": "Isotope le plus stable ²⁸²Rg avec une demi-vie d'environ 2,1 minutes ; analogue prédit de l'or, mais effets relativistes attendus très marqués.",
        "uses": ["Aucune application pratique - recherche fondamentale uniquement"],
        "role": "Étude théorique des effets relativistes extrêmes sur la chimie des métaux nobles (groupe 11).",
    },
    112: {
        "occurrence": "Synthétisé le 9 février 1996 au GSI de Darmstadt par fusion froide de plomb-208 avec des ions zinc-70.",
        "specificity": "Isotope le plus stable ²⁸⁵Cn avec une demi-vie d'environ 29 secondes ; prédit volatil voire gazeux à température ambiante en raison d'effets relativistes intenses, analogue lourd du mercure.",
        "uses": ["Aucune application pratique - recherche fondamentale uniquement"],
        "role": "Test des prédictions relativistes sur la chimie du groupe 12 (chimie en phase gazeuse sur surfaces d'or).",
    },
    113: {
        "occurrence": "Synthétisé en 2004 par l'équipe du RIKEN (Wakō, Japon) sous la direction de Kosuke Morita, par fusion froide de bismuth-209 avec des ions zinc-70.",
        "specificity": "Isotope le plus stable ²⁸⁶Nh avec une demi-vie d'environ 19,6 secondes ; premier élément découvert en Asie, baptisé d'après « Nihon » (Japon).",
        "uses": ["Aucune application pratique - recherche fondamentale uniquement"],
        "role": "Confirmation de l'éka-thallium prédit par Mendeleïev et exploration de la chimie du groupe 13 superlourd.",
    },
    114: {
        "occurrence": "Synthétisé en décembre 1998 au laboratoire Flerov (FLNR) à Dubna par fusion chaude de plutonium-244 avec des ions calcium-48.",
        "specificity": "Isotope ²⁸⁹Fl avec une demi-vie d'environ 2,6 secondes ; candidat clé pour l'îlot de stabilité (Z=114 prédit magique), comportement chimique potentiellement proche des gaz nobles.",
        "uses": ["Aucune application pratique - recherche fondamentale uniquement"],
        "role": "Exploration centrale de l'îlot de stabilité nucléaire et test de la magicité du nombre 114 de protons.",
    },
    115: {
        "occurrence": "Synthétisé en août 2003 au JINR de Dubna (collaboration russo-américaine avec Lawrence Livermore) par les réactions ²⁴³Am + ⁴⁸Ca produisant ²⁸⁷/²⁸⁸Mc.",
        "specificity": "Isotope le plus stable ²⁸⁹Mc avec une demi-vie d'environ 220 millisecondes ; ses chaînes de désintégration alpha mènent au nihonium, renforçant l'hypothèse de l'îlot de stabilité.",
        "uses": ["Aucune application pratique - recherche fondamentale uniquement"],
        "role": "Cartographie des chaînes de désintégration alpha menant vers la région de stabilité prédite.",
    },
    116: {
        "occurrence": "Synthétisé le 19 juillet 2000 au JINR de Dubna par l'équipe de Iouri Oganessian via bombardement de curium-248 avec des ions calcium-48.",
        "specificity": "Isotope le plus stable ²⁹³Lv avec une demi-vie d'environ 53 millisecondes ; nommé en l'honneur du Lawrence Livermore National Laboratory, analogue prédit du polonium.",
        "uses": ["Aucune application pratique - recherche fondamentale uniquement"],
        "role": "Étude des chalcogènes superlourds (groupe 16) et exploration des limites de la stabilité nucléaire.",
    },
    117: {
        "occurrence": "Synthétisé en janvier 2010 au JINR de Dubna par fusion de berkélium-249 (cible produite à Oak Ridge) avec des ions calcium-48, confirmé au GSI en 2014.",
        "specificity": "Isotope le plus stable ²⁹⁴Ts avec une demi-vie d'environ 51 millisecondes ; avant-dernier élément du tableau, propriétés intermédiaires entre halogène et métal pauvre.",
        "uses": ["Aucune application pratique - recherche fondamentale uniquement"],
        "role": "Sondage du groupe 17 superlourd et soutien expérimental à l'îlot de stabilité prédit par Seaborg.",
    },
    118: {
        "occurrence": "Synthétisé en 2002 au laboratoire Flerov (FLNR) de Dubna (collaboration JINR / Lawrence Livermore) par fusion de californium-249 avec des ions calcium-48.",
        "specificity": "Élément le plus lourd connu, isotope ²⁹⁴Og avec une demi-vie de seulement 0,7 ms ; seul élément nommé d'après une personne vivante (Iouri Oganessian), achève la 7ᵉ période du tableau périodique.",
        "uses": ["Aucune application pratique - recherche fondamentale uniquement"],
        "role": "Test des limites du tableau périodique et étude prédictive d'un « gaz noble » non noble dû aux effets relativistes extrêmes.",
    },
}
