# Generated by Django 5.2.14 on 2026-05-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SIConstant',
            fields=[
                ('slug', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('value', models.CharField(help_text='Valeur exacte', max_length=80)),
                ('name', models.CharField(max_length=100)),
                ('defines', models.CharField(help_text='Unité définie', max_length=40)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('slug', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=60)),
                ('quantity', models.CharField(help_text='Grandeur mesurée', max_length=80)),
                ('group', models.CharField(choices=[('base', 'Unités de base'), ('derived', 'Unités dérivées'), ('accepted', 'Hors-SI acceptées')], default='derived', max_length=10)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('definition', models.TextField()),
                ('formula', models.CharField(blank=True, default='', max_length=200)),
                ('formula_legend', models.JSONField(blank=True, default=list, help_text='[{symbol, description}]')),
                ('history', models.JSONField(blank=True, default=list, help_text='[{year, text}]')),
                ('conversions', models.JSONField(blank=True, default=list, help_text='[{from, to}]')),
                ('pitfalls', models.JSONField(blank=True, default=list, help_text='[str]')),
            ],
            options={
                'ordering': ['group', 'order', 'slug'],
            },
        ),
    ]
