# Generated by Django 5.2.14 on 2026-05-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('slug', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('icon', models.CharField(max_length=4)),
                ('category', models.CharField(choices=[('combustion', 'Combustion'), ('acid-base', 'Acide-base'), ('redox', 'Oxydoréduction'), ('precipitation', 'Précipitation'), ('synthesis', 'Synthèse'), ('decomposition', 'Décomposition'), ('substitution', 'Substitution'), ('organic', 'Réaction organique')], max_length=20)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('equation', models.CharField(help_text="Équation type, ex: 'CH4 + 2 O2 -> CO2 + 2 H2O'", max_length=200)),
                ('definition', models.TextField()),
                ('principle', models.TextField()),
                ('energetics', models.CharField(blank=True, choices=[('exothermic', 'Exothermique'), ('endothermic', 'Endothermique'), ('athermic', 'Athermique')], default='', max_length=15)),
                ('mechanism', models.JSONField(blank=True, default=list, help_text='[{step:1, text:"..."}]')),
                ('examples', models.JSONField(blank=True, default=list, help_text='[{name, equation, notes}]')),
                ('key_concepts', models.JSONField(blank=True, default=list)),
                ('pitfalls', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['order', 'slug'],
            },
        ),
    ]
