# Generated by Django 5.2.14 on 2026-05-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reaction',
            options={'ordering': ['category', 'order', 'slug']},
        ),
        migrations.AlterField(
            model_name='reaction',
            name='category',
            field=models.CharField(choices=[('redox', "A. Transfert d'électrons (REDOX)"), ('acid-base', 'B. Transfert de protons (acide-base)'), ('structure', 'C. Réarrangement de liaisons (structure)'), ('solids', 'D. Formation / rupture de solides (équilibres)')], max_length=20),
        ),
    ]
