# Generated by Django 5.2.14 on 2026-05-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BondType',
            fields=[
                ('slug', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('icon', models.CharField(max_length=4)),
                ('category', models.CharField(choices=[('intra', 'Liaison intramoléculaire'), ('inter', 'Liaison intermoléculaire'), ('theory', 'Théorie de la liaison')], max_length=10)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('year', models.CharField(blank=True, default='', max_length=20)),
                ('discovered_by', models.CharField(blank=True, default='', max_length=120)),
                ('definition', models.TextField()),
                ('principle', models.TextField()),
                ('energy_range', models.CharField(blank=True, default='', help_text='ex : 400-1000 kJ/mol (ordre de grandeur)', max_length=80)),
                ('examples', models.JSONField(blank=True, default=list, help_text='[{formula, name, notes}]')),
                ('key_concepts', models.JSONField(blank=True, default=list, help_text='[str]')),
                ('pitfalls', models.JSONField(blank=True, default=list, help_text='[str]')),
            ],
            options={
                'ordering': ['category', 'order', 'slug'],
            },
        ),
    ]
