# Generated by Django 5.2.14 on 2026-05-25 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('code', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=80)),
                ('color', models.CharField(help_text='Couleur HSL/hex', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('code', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=400)),
                ('note', models.TextField(blank=True, default='')),
                ('verifies', models.JSONField(blank=True, default=list, help_text='Liste des champs vérifiés')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('Z', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=4)),
                ('name_fr', models.CharField(max_length=40)),
                ('mass', models.FloatField(help_text='Masse atomique (u)')),
                ('period', models.PositiveSmallIntegerField()),
                ('group', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('block', models.CharField(choices=[('s', 's'), ('p', 'p'), ('d', 'd'), ('f', 'f')], max_length=1)),
                ('electronegativity', models.FloatField(blank=True, null=True)),
                ('atomic_radius', models.PositiveIntegerField(blank=True, help_text='pm', null=True)),
                ('ionization_energy', models.FloatField(blank=True, help_text='kJ/mol', null=True)),
                ('density', models.FloatField(blank=True, help_text='g/cm³', null=True)),
                ('year', models.IntegerField(blank=True, help_text='0 = antiquité', null=True)),
                ('color', models.CharField(help_text='Couleur CPK', max_length=10)),
                ('state', models.CharField(choices=[('solid', 'Solide'), ('liquid', 'Liquide'), ('gas', 'Gazeux'), ('synthetic', 'Synthétique')], max_length=10)),
                ('occurrence', models.TextField(blank=True, default='')),
                ('specificity', models.TextField(blank=True, default='')),
                ('uses', models.JSONField(blank=True, default=list)),
                ('role', models.TextField(blank=True, default='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elements', to='elements.category')),
            ],
            options={
                'ordering': ['Z'],
            },
        ),
    ]
