# Generated by Django 5.2.14 on 2026-05-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='electron_affinity',
            field=models.FloatField(blank=True, help_text='Affinité électronique (kJ/mol)', null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='ionization_energies',
            field=models.JSONField(blank=True, default=list, help_text='IE1, IE2, IE3, ... en kJ/mol'),
        ),
        migrations.AddField(
            model_name='element',
            name='valid_charges',
            field=models.JSONField(blank=True, default=list, help_text="États d'oxydation observés (ex : [0, +2, +3] pour le fer)"),
        ),
    ]
