"""Données initiales pour les unités de mesure du SI + hors-SI courantes."""

SI_CONSTANTS = [
    # (slug, symbol, value, name, defines, order)
    ('cs',  'Δν(Cs)', '9 192 631 770 Hz',         "Transition hyperfine du ¹³³Cs", 'seconde',     1),
    ('c',   'c',      '299 792 458 m/s',          "Vitesse de la lumière",          'mètre',       2),
    ('h',   'h',      '6,626 070 15 × 10⁻³⁴ J·s', "Constante de Planck",            'kilogramme',  3),
    ('e',   'e',      '1,602 176 634 × 10⁻¹⁹ C',  "Charge élémentaire",             'ampère',      4),
    ('kb',  'kB',     '1,380 649 × 10⁻²³ J/K',    "Constante de Boltzmann",         'kelvin',      5),
    ('na',  'NA',     '6,022 140 76 × 10²³ /mol', "Constante d'Avogadro",           'mole',        6),
    ('kcd', 'Kcd',    '683 lm/W à 540 THz',       "Efficacité lumineuse",           'candela',     7),
]


def _u(slug, symbol, name, quantity, group, order, definition, formula='',
       formula_legend=None, history=None, conversions=None, pitfalls=None):
    return dict(
        slug=slug, symbol=symbol, name=name, quantity=quantity,
        group=group, order=order, definition=definition, formula=formula,
        formula_legend=formula_legend or [],
        history=history or [],
        conversions=conversions or [],
        pitfalls=pitfalls or [],
    )


UNITS = [
    # ─────────────────────────────  UNITÉS DE BASE  ─────────────────────────────
    _u('metre', 'm', 'Mètre', 'Longueur', 'base', 1,
        definition="Distance parcourue par la lumière dans le vide pendant 1/299 792 458 de seconde. Depuis 2019, c est fixée par convention (299 792 458 m/s exact).",
        formula='d = c × t',
        formula_legend=[
            {'symbol': 'd', 'description': "Distance parcourue (en mètres)"},
            {'symbol': 'c', 'description': "Vitesse de la lumière dans le vide (constante fixée à 299 792 458 m/s)"},
            {'symbol': 't', 'description': "Durée du trajet (en secondes)"},
        ],
        history=[
            {'year': 1791, 'text': "Défini comme la 10 000 000ᵉ partie du quart du méridien terrestre passant par Paris (Delambre & Méchain, 1792-1799)."},
            {'year': 1889, 'text': "Étalon physique : barre en alliage platine-iridium (90/10), conservée à Sèvres."},
            {'year': 1960, 'text': "1 650 763,73 longueurs d'onde de la raie orange du krypton-86 dans le vide."},
            {'year': 1983, 'text': "Définition actuelle : la lumière, donc constante c fixée comme convention."},
            {'year': 2019, 'text': "Redéfinition cohérente du SI : c reste la constante de référence."},
        ],
        conversions=[
            {'from': '1 m', 'to': '100 cm = 1 000 mm = 10⁶ µm'},
            {'from': '1 m', 'to': '10⁻³ km'},
            {'from': '1 m', 'to': '3,2808 ft (pied)'},
            {'from': '1 m', 'to': '39,3701 in (pouce)'},
            {'from': '1 km', 'to': '0,6214 mile (terrestre) = 0,5400 nautique'},
            {'from': '1 année-lumière', 'to': '9,461 × 10¹⁵ m'},
        ],
        pitfalls=[
            "Le mile a deux définitions : terrestre (1 609,344 m) et nautique (1 852 m exact).",
            "L'année-lumière est une distance, pas une durée.",
            "« m » (mètre) à ne pas confondre avec « M » (méga, préfixe 10⁶).",
            "L'angström (Å = 10⁻¹⁰ m) n'est pas SI mais reste très utilisé en cristallographie.",
        ]),
    _u('kilogram', 'kg', 'Kilogramme', 'Masse', 'base', 2,
        definition="Défini en fixant la constante de Planck h = 6,626 070 15 × 10⁻³⁴ J·s. Mesuré expérimentalement via la balance de Kibble qui équilibre une masse contre une force électromagnétique calibrée.",
        formula='1 kg ≡ h × (Δν_Cs · Hz⁻¹) / (c² × constante)',
        formula_legend=[
            {'symbol': 'h',     'description': "Constante de Planck - relie l'énergie d'un photon à sa fréquence (E = h·f). Valeur fixée à 6,626 070 15 × 10⁻³⁴ J·s."},
            {'symbol': 'c',     'description': "Vitesse de la lumière (rejoint la définition du mètre)"},
            {'symbol': 'Δν_Cs', 'description': "Fréquence de transition du césium-133 (définit la seconde)"},
            {'symbol': 'Kibble','description': "La « balance de Kibble » mesure une masse en comparant une force gravitationnelle à une force électromagnétique calibrée via h."},
        ],
        history=[
            {'year': 1795, 'text': "Défini comme la masse d'un litre d'eau pure à 4 °C (sa densité maximale)."},
            {'year': 1889, 'text': "Étalon physique : cylindre de platine-iridium (« le Grand K ») à Sèvres."},
            {'year': 1950, 'text': "Constat : le Grand K dérive de quelques µg par siècle vs ses copies - l'étalon physique devient un problème."},
            {'year': 2019, 'text': "Le 20 mai, redéfinition par fixation de h. Adieu le Grand K - la masse devient mesurable n'importe où."},
        ],
        conversions=[
            {'from': '1 kg', 'to': '1 000 g = 10⁶ mg'},
            {'from': '1 kg', 'to': '2,2046 lb (livre)'},
            {'from': '1 kg', 'to': '35,274 oz (once)'},
            {'from': '1 t (tonne métrique)', 'to': '1 000 kg'},
            {'from': '1 ton (US, courte)', 'to': '907,18 kg'},
            {'from': '1 long ton (UK)', 'to': '1 016,05 kg'},
        ],
        pitfalls=[
            "Seule unité SI de base contenant un préfixe (« kilo ») - historique, jamais corrigé.",
            "Masse (kg) ≠ poids (N) : sur la Lune, votre masse est inchangée, votre poids est divisé par 6.",
            "« lb » peut signifier livre-masse OU livre-force selon le contexte (ingénierie US).",
            "La tonne métrique (1 000 kg) diffère du ton US (907 kg) et du long ton britannique (1 016 kg).",
        ]),
    _u('second', 's', 'Seconde', 'Temps', 'base', 3,
        definition="Durée de 9 192 631 770 cycles du rayonnement correspondant à la transition entre les deux niveaux hyperfins de l'état fondamental de l'atome de césium-133 au repos, à 0 K.",
        formula='1 s = 9 192 631 770 × T_Cs',
        formula_legend=[
            {'symbol': 'Δν_Cs', 'description': "Fréquence de la transition hyperfine du césium-133 (valeur fixée à 9 192 631 770 Hz)"},
            {'symbol': 'T_Cs',  'description': "Période d'une oscillation = 1/Δν_Cs (la durée d'un seul cycle)"},
        ],
        history=[
            {'year': -2000, 'text': "Antiquité : 1/86 400 d'un jour solaire moyen."},
            {'year': 1956, 'text': "Seconde des éphémérides : fraction définie de l'année tropique 1900 (problème : pas reproductible facilement)."},
            {'year': 1967, 'text': "Définition atomique actuelle, adoptée par la 13ᵉ CGPM."},
            {'year': 2019, 'text': "Reformulation : Δν_Cs fixée à 9 192 631 770 Hz exact."},
        ],
        conversions=[
            {'from': '1 min', 'to': '60 s'},
            {'from': '1 h', 'to': '3 600 s'},
            {'from': '1 jour', 'to': '86 400 s'},
            {'from': '1 année julienne', 'to': '31 557 600 s (365,25 j)'},
            {'from': '1 année tropique', 'to': '≈ 31 556 925 s (365,2422 j)'},
        ],
        pitfalls=[
            "L'année n'est pas SI : sa durée dépend de la convention (julienne, tropique, sidérale).",
            "Les secondes intercalaires (leap seconds) sont ajoutées à UTC pour rester proches de la rotation terrestre - supprimées à partir de 2035.",
            "Les horloges atomiques modernes (Sr-87, Yb-171) sont 100× plus précises que le Cs - redéfinition probable de la seconde dans les années 2030.",
        ]),
    _u('ampere', 'A', 'Ampère', 'Courant électrique', 'base', 4,
        definition="Défini en fixant la charge élémentaire e = 1,602 176 634 × 10⁻¹⁹ C. 1 A correspond à un débit d'environ 6,24 × 10¹⁸ électrons par seconde.",
        formula='I = dQ/dt',
        formula_legend=[
            {'symbol': 'I',     'description': "Intensité du courant (en ampères)"},
            {'symbol': 'Q',     'description': "Charge électrique (en coulombs, C = A·s)"},
            {'symbol': 't',     'description': "Temps (en secondes)"},
            {'symbol': 'dQ/dt', 'description': "Variation de charge par unité de temps - autrement dit le « débit » de charges électriques"},
            {'symbol': 'e',     'description': "Charge élémentaire d'un électron (≈ 1,602 × 10⁻¹⁹ C). Fixe la définition depuis 2019."},
        ],
        history=[
            {'year': 1881, 'text': "Premier ampère « international » : courant déposant 1,118 mg d'argent par seconde par électrolyse."},
            {'year': 1948, 'text': "Ampère « SI » : force entre deux fils parallèles infinis (2 × 10⁻⁷ N/m pour 1 A)."},
            {'year': 2019, 'text': "Redéfinition par e : indépendant de toute géométrie expérimentale."},
        ],
        conversions=[
            {'from': '1 A', 'to': '1 000 mA = 10⁶ µA'},
            {'from': '1 A', 'to': '6,2415 × 10¹⁸ électrons/s'},
            {'from': '1 A', 'to': '1 C/s'},
        ],
        pitfalls=[
            "Sens conventionnel du courant (de + vers −) ≠ sens réel des électrons (de − vers +).",
            "Courant alternatif : la valeur affichée est typiquement la RMS (efficace), pas le pic. 230 V RMS ≈ 325 V crête.",
            "Ampère-heure (Ah) est une charge, pas un courant : 1 Ah = 3 600 C.",
        ]),
    _u('kelvin', 'K', 'Kelvin', 'Température', 'base', 5,
        definition="Défini en fixant la constante de Boltzmann kB = 1,380 649 × 10⁻²³ J/K. Le zéro kelvin (0 K) correspond au zéro absolu, où l'agitation thermique cesse (impossible à atteindre physiquement).",
        formula='E_thermique ∝ kB · T',
        formula_legend=[
            {'symbol': 'E_thermique', 'description': "Énergie d'agitation d'une particule (en joules)"},
            {'symbol': 'kB',          'description': "Constante de Boltzmann - relie température et énergie microscopique. Valeur fixée à 1,380 649 × 10⁻²³ J/K."},
            {'symbol': 'T',           'description': "Température absolue (en kelvins, 0 K = zéro absolu)"},
        ],
        history=[
            {'year': 1848, 'text': "William Thomson (Lord Kelvin) propose une échelle de température absolue."},
            {'year': 1954, 'text': "0,01 °C (point triple de l'eau) fixé à 273,16 K exact."},
            {'year': 2019, 'text': "Définition via kB - le point triple de l'eau redevient une mesure."},
        ],
        conversions=[
            {'from': '0 K', 'to': '−273,15 °C = −459,67 °F (zéro absolu)'},
            {'from': '273,15 K', 'to': '0 °C = 32 °F (fusion glace)'},
            {'from': '373,15 K', 'to': '100 °C = 212 °F (ébullition eau à 1 atm)'},
            {'from': 'T(°C)', 'to': 'T(K) − 273,15'},
            {'from': 'T(°F)', 'to': 'T(°C) × 9/5 + 32'},
        ],
        pitfalls=[
            "On écrit « 300 K », pas « 300 °K » (le degré a été supprimé en 1967).",
            "Les écarts (différences) de température sont identiques en K et en °C ; les valeurs absolues diffèrent de 273,15.",
            "Échelle Rankine (°R) : Kelvin × 9/5 - utilisée en ingénierie aux États-Unis.",
        ]),
    _u('mole', 'mol', 'Mole', 'Quantité de matière', 'base', 6,
        definition="Quantité de matière contenant exactement 6,022 140 76 × 10²³ entités élémentaires (atomes, molécules, ions, électrons…). Cette valeur définit la constante d'Avogadro NA.",
        formula='n = N / NA',
        formula_legend=[
            {'symbol': 'n',  'description': "Quantité de matière (en moles)"},
            {'symbol': 'N',  'description': "Nombre d'entités élémentaires (atomes, molécules, ions…)"},
            {'symbol': 'NA', 'description': "Constante d'Avogadro - nombre d'entités dans une mole. Valeur fixée à 6,022 140 76 × 10²³."},
        ],
        history=[
            {'year': 1865, 'text': "Loschmidt estime le nombre d'atomes dans un volume de gaz."},
            {'year': 1909, 'text': "Perrin baptise « nombre d'Avogadro » et le mesure (Nobel 1926)."},
            {'year': 1971, 'text': "Mole introduite comme unité SI de base : masse de 12 g de carbone-12."},
            {'year': 2019, 'text': "Redéfinition : NA fixé exactement, sans plus dépendre de la masse du carbone."},
        ],
        conversions=[
            {'from': '1 mol', 'to': '6,022 140 76 × 10²³ entités'},
            {'from': '1 mol H₂O', 'to': '18,015 g'},
            {'from': '1 mol gaz idéal', 'to': '22,414 L à 0 °C et 1 atm'},
            {'from': '1 mmol', 'to': '10⁻³ mol'},
        ],
        pitfalls=[
            "« 12 g = 1 mol de carbone » : exact pour ¹²C pur, approximation pour le C naturel (M = 12,011 g/mol).",
            "Molarité (mol/L) ≠ molalité (mol/kg solvant) ≠ fraction molaire (sans unité).",
            "La mole compte des entités, pas des masses - préciser toujours laquelle (atomes, molécules, paires d'ions).",
        ]),
    _u('candela', 'cd', 'Candela', 'Intensité lumineuse', 'base', 7,
        definition="Intensité lumineuse, dans une direction donnée, d'une source émettant un rayonnement monochromatique à 540 × 10¹² Hz (vert-jaune) dont l'intensité énergétique est 1/683 W/sr. Définie en fixant Kcd = 683 lm/W.",
        formula='I_v = Kcd × ∫ V(λ) · (dΦ_e/dλ) dλ',
        formula_legend=[
            {'symbol': 'I_v',  'description': "Intensité lumineuse perçue par l'œil humain (en candelas)"},
            {'symbol': 'Kcd',  'description': "Constante d'efficacité lumineuse - fixée à 683 lm/W à 540 THz (lumière verte, là où l'œil voit le mieux)"},
            {'symbol': 'V(λ)', 'description': "Courbe de sensibilité de l'œil humain selon la longueur d'onde - vaut 1 dans le vert, 0 dans l'infrarouge et l'ultraviolet"},
            {'symbol': 'Φ_e',  'description': "Flux énergétique total émis (en watts)"},
            {'symbol': 'λ',    'description': "Longueur d'onde de la lumière (en mètres)"},
            {'symbol': '∫… dλ','description': "Intégrale : somme des contributions de toutes les longueurs d'onde"},
        ],
        history=[
            {'year': 1860, 'text': "Bougie standard anglaise (luminosité d'une bougie de spermaceti brûlant à 7,77 g/h)."},
            {'year': 1948, 'text': "Candela : 1/60 de l'intensité d'un cm² de corps noir à la température de solidification du platine."},
            {'year': 1979, 'text': "Redéfinition par la longueur d'onde de 540 THz (sensibilité max de l'œil humain)."},
        ],
        conversions=[
            {'from': '1 cd', 'to': '1 lm/sr (lumens par stéradian)'},
            {'from': 'Bougie domestique', 'to': '≈ 12 cd'},
            {'from': 'Phare automobile', 'to': '≈ 35 000 cd'},
        ],
        pitfalls=[
            "Trois unités lumineuses à ne pas confondre : candela (intensité dans une direction), lumen (flux total émis), lux (éclairement = lm/m²).",
            "Les LED sont vendues en lumens (flux), pas en candelas.",
            "La candela est pondérée par la sensibilité de l'œil humain (courbe V(λ)) : 1 W de lumière verte = 683 lm, 1 W d'infrarouge = 0 lm.",
        ]),

    # ─────────────────────────────  UNITÉS DÉRIVÉES  ─────────────────────────────
    _u('radian', 'rad', 'Radian', 'Angle plan', 'derived', 10,
        definition="Angle plan correspondant à un arc de longueur égale au rayon du cercle.",
        formula='θ = L_arc / R',
        formula_legend=[
            {'symbol': 'θ',     'description': "Angle plan (en radians)"},
            {'symbol': 'L_arc', 'description': "Longueur de l'arc de cercle parcouru"},
            {'symbol': 'R',     'description': "Rayon du cercle"},
        ],
        history=[
            {'year': 1714, 'text': "Notion introduite par Roger Cotes (Cambridge)."},
            {'year': 1873, 'text': "Le terme « radian » apparaît à Belfast."},
        ],
        conversions=[
            {'from': '1 rad', 'to': '57,2958° (≈ 180/π)'},
            {'from': '2π rad', 'to': '360° (tour complet)'},
            {'from': '1°', 'to': '0,017 453 rad (= π/180)'},
        ],
        pitfalls=[
            "Beaucoup de bibliothèques (sin, cos…) travaillent en radians, pas en degrés.",
            "Le grade (gon) = 1/400 de tour, utilisé en topographie française.",
        ]),
    _u('steradian', 'sr', 'Stéradian', 'Angle solide', 'derived', 11,
        definition="Angle solide intercepté par une portion de sphère d'aire égale au carré du rayon.",
        formula='Ω = A / R²',
        formula_legend=[
            {'symbol': 'Ω', 'description': "Angle solide (en stéradians)"},
            {'symbol': 'A', 'description': "Aire de la calotte sphérique « vue »"},
            {'symbol': 'R', 'description': "Rayon de la sphère"},
        ],
        history=[{'year': 1881, 'text': "Adopté par le BIPM avec le radian."}],
        conversions=[
            {'from': 'Sphère entière', 'to': '4π sr ≈ 12,566 sr'},
            {'from': 'Hémisphère', 'to': '2π sr ≈ 6,283 sr'},
        ],
        pitfalls=[
            "Un stéradian ne correspond pas à un cercle plan ; représente une « calotte » sphérique.",
            "Souvent omis dans les unités dérivées (W/sr → cd) car sans dimension.",
        ]),
    _u('hertz', 'Hz', 'Hertz', 'Fréquence', 'derived', 12,
        definition="Nombre de cycles complets par seconde d'un phénomène périodique.",
        formula='f = 1 / T',
        formula_legend=[
            {'symbol': 'f', 'description': "Fréquence (nombre de cycles par seconde, en hertz)"},
            {'symbol': 'T', 'description': "Période - durée d'un cycle complet (en secondes)"},
        ],
        history=[
            {'year': 1888, 'text': "Heinrich Hertz démontre l'existence des ondes électromagnétiques prédites par Maxwell."},
            {'year': 1930, 'text': "L'unité « hertz » est adoptée en son honneur, remplaçant « cycles per second »."},
        ],
        conversions=[
            {'from': '1 kHz', 'to': '10³ Hz (audio)'},
            {'from': '1 MHz', 'to': '10⁶ Hz (radio FM)'},
            {'from': '1 GHz', 'to': '10⁹ Hz (Wi-Fi, micro-ondes)'},
            {'from': '1 THz', 'to': '10¹² Hz (infrarouge lointain)'},
        ],
        pitfalls=[
            "Fréquence (Hz) ≠ pulsation (rad/s) : ω = 2π · f.",
            "Hz pour phénomènes périodiques uniquement ; pour comptages discrets, utiliser s⁻¹.",
            "Bq (becquerel) = s⁻¹ aussi, mais désintégrations aléatoires (pas Hz).",
        ]),
    _u('newton', 'N', 'Newton', 'Force', 'derived', 13,
        definition="Force qui communique à un corps de masse 1 kg une accélération de 1 m/s².",
        formula='F = m · a',
        formula_legend=[
            {'symbol': 'F', 'description': "Force exercée (en newtons)"},
            {'symbol': 'm', 'description': "Masse du corps (en kilogrammes)"},
            {'symbol': 'a', 'description': "Accélération produite (en m/s²)"},
        ],
        history=[
            {'year': 1687, 'text': "Newton publie les Principia : F = ma."},
            {'year': 1948, 'text': "Le « newton » est officialisé comme unité SI."},
        ],
        conversions=[
            {'from': '1 N', 'to': '100 000 dyn (CGS)'},
            {'from': '1 kgf (kilogramme-force)', 'to': "9,80665 N (poids d'1 kg sur Terre)"},
            {'from': '1 lbf (livre-force)', 'to': '4,4482 N'},
        ],
        pitfalls=[
            "Le « poids » d'un objet est une force (N), pas une masse (kg) - bien que confondus dans la vie courante.",
            "1 « kilo de pommes » est un abus : c'est 1 kg de masse, soit 9,8 N de poids sur Terre.",
            "« kilonewton-mètre » (kN·m) pour les couples ; ne pas confondre avec énergie (J = N·m), même dimension mais sens physique distinct.",
        ]),
    _u('pascal', 'Pa', 'Pascal', 'Pression', 'derived', 14,
        definition="Force d'1 newton appliquée uniformément sur une surface d'1 m².",
        formula='P = F / A',
        formula_legend=[
            {'symbol': 'P', 'description': "Pression (en pascals)"},
            {'symbol': 'F', 'description': "Force normale exercée sur la surface (en newtons)"},
            {'symbol': 'A', 'description': "Aire de la surface (en m²)"},
        ],
        history=[
            {'year': 1648, 'text': "Blaise Pascal démontre l'existence de la pression atmosphérique (expérience du Puy de Dôme)."},
            {'year': 1971, 'text': "Pascal adopté comme unité SI dérivée."},
        ],
        conversions=[
            {'from': '1 atm', 'to': '101 325 Pa = 1 013,25 hPa'},
            {'from': '1 bar', 'to': '100 000 Pa = 1 000 hPa'},
            {'from': '1 mmHg (Torr)', 'to': '133,322 Pa'},
            {'from': '1 psi (livre/pouce²)', 'to': '6 894,76 Pa'},
            {'from': '1 mb (millibar)', 'to': '1 hPa = 100 Pa'},
        ],
        pitfalls=[
            "Pression atmosphérique en météo : hPa = mbar (équivalents).",
            "psi vs psia (absolue) vs psig (relative à atm) - confusion fréquente.",
            "L'altimètre d'avion utilise la pression : un mauvais réglage du QNH peut être fatal.",
        ]),
    _u('joule', 'J', 'Joule', 'Énergie / travail', 'derived', 15,
        definition="Travail produit par une force d'1 newton appliquée sur 1 mètre dans sa direction.",
        formula='W = F · d',
        formula_legend=[
            {'symbol': 'W', 'description': "Travail / énergie transférée (en joules)"},
            {'symbol': 'F', 'description': "Force exercée (en newtons)"},
            {'symbol': 'd', 'description': "Déplacement dans la direction de la force (en mètres)"},
            {'symbol': '1 J', 'description': "Équivaut aussi à 1 W·s (puissance × temps) ou 1 C·V (charge × tension)"},
        ],
        history=[
            {'year': 1843, 'text': "James Joule établit l'équivalence travail-chaleur (4,184 J ≈ 1 cal)."},
            {'year': 1948, 'text': "Le joule devient l'unité SI d'énergie."},
        ],
        conversions=[
            {'from': '1 cal (thermochimique)', 'to': '4,184 J'},
            {'from': '1 kcal (« Calorie » nutritionnelle)', 'to': '4 184 J = 4,184 kJ'},
            {'from': '1 Wh', 'to': '3 600 J = 3,6 kJ'},
            {'from': '1 kWh', 'to': '3,6 × 10⁶ J = 3,6 MJ'},
            {'from': '1 eV', 'to': '1,602 × 10⁻¹⁹ J'},
            {'from': '1 BTU', 'to': '1 055,06 J'},
        ],
        pitfalls=[
            "La « Calorie » nutritionnelle (avec C majuscule) = 1 kcal = 1 000 cal physiques.",
            "Deux définitions de la calorie : thermochimique (4,184 J) et internationale (4,1868 J).",
            "Ne pas confondre J (énergie, scalaire) et N·m (couple, vectoriel) - même dimension, sens différent.",
        ]),
    _u('watt', 'W', 'Watt', 'Puissance', 'derived', 16,
        definition="Puissance correspondant à un transfert d'énergie d'1 joule par seconde.",
        formula='P = E / t = U · I',
        formula_legend=[
            {'symbol': 'P', 'description': "Puissance (en watts)"},
            {'symbol': 'E', 'description': "Énergie transférée (en joules)"},
            {'symbol': 't', 'description': "Durée du transfert (en secondes)"},
            {'symbol': 'U', 'description': "Tension électrique (en volts, contexte électrique)"},
            {'symbol': 'I', 'description': "Intensité du courant (en ampères, contexte électrique)"},
        ],
        history=[
            {'year': 1782, 'text': "James Watt améliore la machine à vapeur ; introduit le « horsepower »."},
            {'year': 1948, 'text': "Le watt remplace le horsepower comme unité SI."},
        ],
        conversions=[
            {'from': '1 hp (cheval-vapeur métrique)', 'to': '735,5 W'},
            {'from': '1 HP (cheval mécanique US)', 'to': '745,7 W'},
            {'from': '1 BTU/h', 'to': '0,293 W'},
            {'from': '1 kW', 'to': '1,3596 hp'},
        ],
        pitfalls=[
            "En courant alternatif, VA (apparente) ≠ W (active) - le facteur de puissance cos(φ) peut être ≤ 1.",
            "Un « kWh » est une énergie (puissance × temps), pas une puissance.",
            "Cheval-vapeur métrique (735,5 W) ≠ horsepower mécanique US (745,7 W).",
        ]),
    _u('coulomb', 'C', 'Coulomb', 'Charge électrique', 'derived', 17,
        definition="Quantité d'électricité transportée par un courant d'1 ampère pendant 1 seconde.",
        formula='Q = I · t',
        formula_legend=[
            {'symbol': 'Q', 'description': "Charge électrique transportée (en coulombs)"},
            {'symbol': 'I', 'description': "Intensité du courant (en ampères)"},
            {'symbol': 't', 'description': "Durée du passage du courant (en secondes)"},
            {'symbol': 'e', 'description': "Charge élémentaire d'un électron (≈ 1,602 × 10⁻¹⁹ C). 1 C ≈ 6,24 × 10¹⁸ charges."},
        ],
        history=[{'year': 1785, 'text': "Charles-Augustin de Coulomb mesure la force entre charges."}],
        conversions=[
            {'from': '1 C', 'to': '6,2415 × 10¹⁸ charges élémentaires (e)'},
            {'from': '1 Ah (ampère-heure)', 'to': '3 600 C'},
            {'from': '1 mAh (capacité batterie)', 'to': '3,6 C'},
        ],
        pitfalls=[
            "Une batterie de 3 000 mAh stocke 10 800 C de charge, pas d'énergie - l'énergie dépend aussi de la tension.",
            "Énergie d'une batterie : E (Wh) = Q (Ah) × U (V).",
        ]),
    _u('volt', 'V', 'Volt', 'Tension / potentiel', 'derived', 18,
        definition="Différence de potentiel entre deux points d'un conducteur traversé par 1 A et dissipant 1 W.",
        formula='U = E / Q',
        formula_legend=[
            {'symbol': 'U', 'description': "Différence de potentiel / tension (en volts)"},
            {'symbol': 'E', 'description': "Énergie nécessaire pour déplacer la charge (en joules)"},
            {'symbol': 'Q', 'description': "Charge déplacée (en coulombs)"},
        ],
        history=[{'year': 1800, 'text': "Alessandro Volta invente la pile (« colonne voltaïque »)."}],
        conversions=[
            {'from': 'Pile AA', 'to': '1,5 V'},
            {'from': 'Batterie auto', 'to': '12 V'},
            {'from': 'Prise secteur Europe', 'to': '230 V RMS (325 V crête)'},
            {'from': 'Ligne haute tension', 'to': '400 kV'},
        ],
        pitfalls=[
            "Tension efficace (RMS) ≠ tension crête : 230 V RMS ≈ 325 V crête en sinusoïdal.",
            "Le « neutre » domestique n'est pas à 0 V (légèrement décalé) ; seule la terre l'est à coup sûr.",
            "Tension absolue (par rapport à la terre) vs différence de potentiel : préciser le contexte.",
        ]),
    _u('ohm', 'Ω', 'Ohm', 'Résistance électrique', 'derived', 19,
        definition="Résistance d'un conducteur où une tension d'1 V produit un courant d'1 A.",
        formula='R = U / I',
        formula_legend=[
            {'symbol': 'R', 'description': "Résistance électrique (en ohms)"},
            {'symbol': 'U', 'description': "Tension aux bornes du conducteur (en volts)"},
            {'symbol': 'I', 'description': "Intensité du courant qui le traverse (en ampères)"},
        ],
        history=[{'year': 1827, 'text': "Georg Simon Ohm publie sa loi."}],
        conversions=[
            {'from': '1 kΩ', 'to': '10³ Ω'},
            {'from': '1 MΩ', 'to': '10⁶ Ω'},
            {'from': 'Impédance du vide Z₀', 'to': '≈ 376,73 Ω'},
        ],
        pitfalls=[
            "Résistance (Ω, statique) ≠ impédance (Ω, en alternatif, complexe).",
            "Conductance G = 1/R, unité siemens (S).",
            "Code des couleurs des résistances : bandes à lire en commençant par celle la plus proche du bord.",
        ]),
    _u('farad', 'F', 'Farad', 'Capacité électrique', 'derived', 20,
        definition="Capacité d'un condensateur qui, sous 1 V, accumule 1 C de charge.",
        formula='C = Q / U',
        formula_legend=[
            {'symbol': 'C', 'description': "Capacité du condensateur (en farads)"},
            {'symbol': 'Q', 'description': "Charge stockée sur une armature (en coulombs)"},
            {'symbol': 'U', 'description': "Tension entre les deux armatures (en volts)"},
        ],
        history=[{'year': 1881, 'text': "Le farad est nommé en l'honneur de Michael Faraday."}],
        conversions=[
            {'from': '1 µF', 'to': '10⁻⁶ F (typique en audio)'},
            {'from': '1 nF', 'to': '10⁻⁹ F (filtrage)'},
            {'from': '1 pF', 'to': '10⁻¹² F (radiofréquence)'},
        ],
        pitfalls=[
            "1 F est énorme : la plupart des condensateurs courants sont en pF, nF ou µF.",
            "Super-capacités (super-caps) atteignent quelques milliers de F - d'où leur intérêt comme tampon entre batterie et moteur.",
        ]),
    _u('siemens', 'S', 'Siemens', 'Conductance électrique', 'derived', 21,
        definition="Inverse de l'ohm.",
        formula='G = 1 / R = I / U',
        formula_legend=[
            {'symbol': 'G', 'description': "Conductance (en siemens)"},
            {'symbol': 'R', 'description': "Résistance (en ohms) - la conductance est son inverse"},
            {'symbol': 'U', 'description': "Tension (en volts)"},
            {'symbol': 'I', 'description': "Intensité du courant (en ampères)"},
        ],
        history=[{'year': 1971, 'text': "Adopté comme nom SI (remplace l'ancien « mho »)."}],
        conversions=[{'from': '1 S', 'to': '1 mho = 1 A/V'}],
        pitfalls=["S (siemens) ne se confond pas avec s (seconde) à l'écrit."]),
    _u('weber', 'Wb', 'Weber', 'Flux magnétique', 'derived', 22,
        definition="Flux qui, traversant un circuit d'1 spire, y induit une fem d'1 V lorsqu'il est annulé uniformément en 1 s.",
        formula='Φ = B · A',
        formula_legend=[
            {'symbol': 'Φ',   'description': "Flux magnétique traversant la surface (en webers)"},
            {'symbol': 'B',   'description': "Induction magnétique (en teslas)"},
            {'symbol': 'A',   'description': "Aire de la surface traversée (en m²)"},
            {'symbol': 'fem', 'description': "Une variation de flux de 1 Wb/s induit une force électromotrice de 1 V (loi de Faraday)"},
        ],
        history=[{'year': 1935, 'text': "Adopté par la CIE en l'honneur de Wilhelm Weber."}],
        conversions=[{'from': '1 Wb', 'to': '10⁸ maxwell (CGS)'}],
        pitfalls=["Flux (Wb) vs induction B (T) vs champ H (A/m) - trois grandeurs distinctes en magnétisme."]),
    _u('tesla', 'T', 'Tesla', 'Induction magnétique', 'derived', 23,
        definition="Induction magnétique uniforme qui produit un flux d'1 Wb à travers 1 m².",
        formula='B = Φ / A',
        formula_legend=[
            {'symbol': 'B', 'description': "Induction magnétique - densité du flux (en teslas)"},
            {'symbol': 'Φ', 'description': "Flux magnétique total (en webers)"},
            {'symbol': 'A', 'description': "Aire perpendiculaire au champ (en m²)"},
        ],
        history=[{'year': 1960, 'text': "Adopté en l'honneur de Nikola Tesla."}],
        conversions=[
            {'from': '1 T', 'to': '10 000 G (gauss, CGS)'},
            {'from': 'Champ magnétique terrestre', 'to': '≈ 25-65 µT'},
            {'from': 'Aimant frigo', 'to': '≈ 5 mT'},
            {'from': 'IRM hospitalière', 'to': '1,5 à 3 T'},
            {'from': 'IRM recherche', 'to': '7 à 11 T'},
        ],
        pitfalls=[
            "T (tesla, induction B) ne se confond pas avec T (kelvin) en contexte.",
            "Le « champ magnétique » désigne ambigument B (T) ou H (A/m) selon les sources.",
        ]),
    _u('henry', 'H', 'Henry', 'Inductance', 'derived', 24,
        definition="Inductance d'un circuit où un courant variant d'1 A/s induit une fem d'1 V.",
        formula='U_induite = L · (dI/dt)',
        formula_legend=[
            {'symbol': 'L',         'description': "Inductance de la bobine (en henrys)"},
            {'symbol': 'U_induite', 'description': "Tension induite aux bornes de la bobine (en volts)"},
            {'symbol': 'dI/dt',     'description': "Vitesse de variation du courant (en A/s)"},
        ],
        history=[{'year': 1893, 'text': "Nommé d'après Joseph Henry."}],
        conversions=[
            {'from': '1 mH', 'to': '10⁻³ H'},
            {'from': '1 µH', 'to': '10⁻⁶ H'},
        ],
        pitfalls=["H (henry) ≠ Hz (hertz). Toujours bien orthographier."]),
    _u('celsius', '°C', 'Degré Celsius', 'Température', 'derived', 25,
        definition="Échelle dérivée du kelvin par décalage de 273,15 : T(°C) = T(K) − 273,15.",
        formula='T(°C) = T(K) − 273,15',
        formula_legend=[
            {'symbol': 'T(°C)',  'description': "Température en degrés Celsius"},
            {'symbol': 'T(K)',   'description': "Température absolue en kelvins"},
            {'symbol': '273,15', 'description': "Décalage entre 0 K (zéro absolu) et 0 °C (fusion de la glace à 1 atm)"},
        ],
        history=[{'year': 1742, 'text': "Anders Celsius propose une échelle inversée (inversée après sa mort)."}],
        conversions=[
            {'from': '0 °C', 'to': '273,15 K = 32 °F'},
            {'from': '100 °C', 'to': '373,15 K = 212 °F'},
            {'from': '−40 °C', 'to': '−40 °F (point de croisement)'},
        ],
        pitfalls=[
            "Les écarts de température sont identiques en °C et K ; les valeurs absolues diffèrent.",
            "« 30 degrés » sans contexte est ambigu (°C ou °F selon le pays).",
        ]),
    _u('lumen', 'lm', 'Lumen', 'Flux lumineux', 'derived', 26,
        definition="Flux lumineux émis par une source de 1 cd dans un angle solide de 1 sr.",
        formula='Φ_v = I_v · Ω',
        formula_legend=[
            {'symbol': 'Φ_v', 'description': "Flux lumineux total émis (en lumens)"},
            {'symbol': 'I_v', 'description': "Intensité lumineuse dans la direction donnée (en candelas)"},
            {'symbol': 'Ω',   'description': "Angle solide traversé (en stéradians)"},
        ],
        history=[{'year': 1948, 'text': "Officialisé en même temps que le candela."}],
        conversions=[
            {'from': 'Bougie', 'to': '≈ 12 lm'},
            {'from': 'Ampoule LED 10 W', 'to': '≈ 1 000 lm'},
        ],
        pitfalls=[
            "Les LED grand public sont étiquetées en lumens, pas en watts.",
            "Efficacité : un W électrique convertit ≈ 100-170 lm pour une bonne LED, ≈ 10-15 lm pour une incandescente.",
        ]),
    _u('lux', 'lx', 'Lux', 'Éclairement', 'derived', 27,
        definition="Éclairement d'une surface recevant uniformément 1 lm sur 1 m².",
        formula='E_v = Φ_v / A',
        formula_legend=[
            {'symbol': 'E_v', 'description': "Éclairement reçu par la surface (en lux)"},
            {'symbol': 'Φ_v', 'description': "Flux lumineux qui arrive (en lumens)"},
            {'symbol': 'A',   'description': "Aire de la surface éclairée (en m²)"},
        ],
        history=[{'year': 1889, 'text': "Adopté en France pour l'éclairage public."}],
        conversions=[
            {'from': 'Nuit étoilée sans lune', 'to': '≈ 0,002 lx'},
            {'from': 'Pleine lune', 'to': '≈ 0,25 lx'},
            {'from': 'Bureau bien éclairé', 'to': '300-500 lx'},
            {'from': 'Soleil direct (été)', 'to': '50 000-100 000 lx'},
        ],
        pitfalls=[
            "Lux dépend de la distance source ↔ surface (1/d² approximativement).",
            "Éclairement (lx) mesure la lumière reçue ; luminance (cd/m²) mesure la lumière perçue depuis une surface.",
        ]),
    _u('becquerel', 'Bq', 'Becquerel', 'Activité radioactive', 'derived', 28,
        definition="Une désintégration nucléaire par seconde.",
        formula='A = − dN/dt = λ · N',
        formula_legend=[
            {'symbol': 'A',     'description': "Activité radioactive (en becquerels)"},
            {'symbol': 'N',     'description': "Nombre de noyaux radioactifs présents à un instant donné"},
            {'symbol': 'dN/dt', 'description': "Variation du nombre de noyaux par seconde (négative car ils se désintègrent)"},
            {'symbol': 'λ',     'description': "Constante de désintégration propre à chaque radionucléide (s⁻¹)"},
        ],
        history=[
            {'year': 1896, 'text': "Henri Becquerel découvre la radioactivité spontanée."},
            {'year': 1975, 'text': "Le becquerel remplace le curie comme unité SI."},
        ],
        conversions=[
            {'from': '1 Ci (curie)', 'to': "3,7 × 10¹⁰ Bq (activité d'1 g de radium)"},
            {'from': 'Banane', 'to': '≈ 15 Bq (potassium-40 naturel)'},
            {'from': 'Corps humain', 'to': '≈ 8 000 Bq (K-40 + C-14)'},
        ],
        pitfalls=[
            "Bq mesure le taux de désintégration, pas la nocivité - il faut connaître le radionucléide.",
            "1 Bq de Po-210 est bien plus dangereux qu'1 Bq de C-14.",
            "Dose biologique : utiliser le sievert (Sv), pas le becquerel.",
        ]),
    _u('gray', 'Gy', 'Gray', 'Dose absorbée', 'derived', 29,
        definition="Énergie de 1 joule absorbée par 1 kg de matière.",
        formula='D = E_abs / m',
        formula_legend=[
            {'symbol': 'D',     'description': "Dose absorbée (en grays)"},
            {'symbol': 'E_abs', 'description': "Énergie de rayonnement absorbée par la matière (en joules)"},
            {'symbol': 'm',     'description': "Masse de matière exposée (en kilogrammes)"},
        ],
        history=[{'year': 1975, 'text': "Adopté en l'honneur de Louis Harold Gray."}],
        conversions=[
            {'from': '1 rad', 'to': '0,01 Gy (ancienne unité)'},
            {'from': 'Radiographie pulmonaire', 'to': '≈ 0,1 mGy'},
            {'from': 'Radiothérapie cancer', 'to': '50-70 Gy (cumulatif)'},
        ],
        pitfalls=[
            "Gy (dose absorbée, physique) ≠ Sv (dose équivalente, biologique).",
            "Même dose en Gy peut donner des effets très différents selon le type de rayonnement.",
        ]),
    _u('sievert', 'Sv', 'Sievert', 'Dose équivalente / efficace', 'derived', 30,
        definition="Dose absorbée multipliée par un facteur de pondération biologique (1 pour β/γ, 20 pour α).",
        formula='H = Σ wR · DR',
        formula_legend=[
            {'symbol': 'H',  'description': "Dose équivalente - effet biologique (en sieverts)"},
            {'symbol': 'DR', 'description': "Dose absorbée pour un type de rayonnement R (en grays)"},
            {'symbol': 'wR', 'description': "Facteur de pondération radiologique : 1 pour β et γ, 20 pour les particules α (sans unité)"},
            {'symbol': 'Σ',  'description': "Somme sur tous les types de rayonnements présents"},
        ],
        history=[{'year': 1979, 'text': "Adopté en l'honneur de Rolf Maximilian Sievert (radioprotection)."}],
        conversions=[
            {'from': '1 rem', 'to': '0,01 Sv (ancienne unité)'},
            {'from': 'Fond naturel annuel', 'to': '≈ 2-3 mSv'},
            {'from': 'Vol Paris-NY', 'to': '≈ 0,05 mSv'},
            {'from': 'Scanner thoracique', 'to': '≈ 7 mSv'},
            {'from': 'Dose mortelle (LD50)', 'to': '≈ 4 Sv en exposition aiguë'},
        ],
        pitfalls=[
            "Sv (effet biologique) ≠ Gy (énergie physique) - Sv = Gy × facteur de pondération.",
            "Limite annuelle réglementaire pour le public en France : 1 mSv.",
            "Le Sv est une grande unité ; on travaille presque toujours en mSv ou µSv.",
        ]),
    _u('katal', 'kat', 'Katal', 'Activité catalytique', 'derived', 31,
        definition="Activité d'une enzyme catalysant 1 mole de substrat par seconde.",
        formula='z = dn / dt',
        formula_legend=[
            {'symbol': 'z',     'description': "Activité catalytique de l'enzyme (en katals)"},
            {'symbol': 'n',     'description': "Quantité de substrat transformé (en moles)"},
            {'symbol': 't',     'description': "Temps (en secondes)"},
            {'symbol': 'dn/dt', 'description': "Vitesse de transformation : moles de substrat converties par seconde"},
        ],
        history=[{'year': 1999, 'text': "Officialisé par la CGPM pour standardiser les mesures enzymatiques."}],
        conversions=[{'from': '1 U (unité enzymatique)', 'to': '16,67 nkat (= 1 µmol/min)'}],
        pitfalls=["Très peu employé en pratique ; les labos restent largement sur l'unité U (1 µmol/min)."]),

    # ─────────────────────────────  HORS-SI ACCEPTÉES  ─────────────────────────────
    _u('litre', 'L', 'Litre', 'Volume', 'accepted', 40,
        definition="Volume égal à 1 décimètre cube (1 dm³).",
        formula='1 L = 1 dm³ = 10⁻³ m³',
        formula_legend=[
            {'symbol': 'L',   'description': "Litre (unité de volume hors-SI mais acceptée)"},
            {'symbol': 'dm³', 'description': "Décimètre cube - cube de 10 cm de côté"},
            {'symbol': 'm³',  'description': "Mètre cube, unité SI de volume (1 m³ = 1 000 L)"},
        ],
        history=[
            {'year': 1795, 'text': "Défini par la Convention française comme volume d'1 kg d'eau pure à 4 °C."},
            {'year': 1964, 'text': "Définition simplifiée : 1 L = 1 dm³ exactement."},
        ],
        conversions=[
            {'from': '1 L', 'to': '1 000 mL = 1 dm³'},
            {'from': '1 m³', 'to': '1 000 L'},
            {'from': '1 gallon US', 'to': '3,7854 L'},
            {'from': '1 gallon UK (imperial)', 'to': '4,5461 L'},
        ],
        pitfalls=[
            "Gallon US ≠ gallon UK : 20% de différence (pétrole, automobile).",
            "Symbole majuscule L recommandé (le « l » minuscule se confond avec le chiffre 1).",
        ]),
    _u('tonne', 't', 'Tonne', 'Masse', 'accepted', 41,
        definition="Mégagramme : 10³ kg.",
        formula='1 t = 1 000 kg = 1 Mg',
        formula_legend=[
            {'symbol': 't',  'description': "Tonne métrique (égale à mille kilogrammes)"},
            {'symbol': 'kg', 'description': "Kilogramme - unité SI de base de la masse"},
            {'symbol': 'Mg', 'description': "Mégagramme - nom officiel SI de la tonne (rarement utilisé)"},
        ],
        history=[{'year': 1880, 'text': "Adopté par la CGPM comme unité métrique courante."}],
        conversions=[
            {'from': '1 tonne métrique', 'to': '1 000 kg'},
            {'from': '1 ton US (courte)', 'to': '907,18 kg'},
            {'from': '1 long ton (UK)', 'to': '1 016,05 kg'},
        ],
        pitfalls=[
            "Tonne métrique (1 000 kg) ≠ ton US (907 kg) ≠ long ton britannique (1 016 kg).",
            "Tonne d'équivalent pétrole (tep) : unité d'énergie (≈ 11,63 MWh), pas de masse.",
        ]),
    _u('minute-hour', 'min, h, j', 'Minute, heure, jour', 'Temps', 'accepted', 42,
        definition="Multiples non décimaux de la seconde, conservés pour des raisons historiques (Babylone, base 60).",
        formula='1 min = 60 s ;  1 h = 3 600 s ;  1 j = 86 400 s',
        formula_legend=[
            {'symbol': 'min', 'description': "Minute (60 secondes)"},
            {'symbol': 'h',   'description': "Heure (60 minutes = 3 600 secondes)"},
            {'symbol': 'j',   'description': "Jour solaire moyen (24 heures = 86 400 secondes)"},
            {'symbol': 's',   'description': "Seconde - unité SI de base"},
        ],
        history=[{'year': -2000, 'text': "Système sexagésimal babylonien (base 60)."}],
        conversions=[
            {'from': '1 j', 'to': '24 h = 1 440 min = 86 400 s'},
            {'from': '1 année (julienne)', 'to': '365,25 j = 31 557 600 s'},
        ],
        pitfalls=[
            "L'année et le mois ne sont pas SI ; éviter pour les calculs scientifiques précis.",
            "Année tropique (365,2422 j) vs julienne (365,25 j) vs grégorienne (365,2425 j).",
        ]),
    _u('ev', 'eV', 'Électron-volt', 'Énergie', 'accepted', 43,
        definition="Énergie acquise par un électron accéléré sous une différence de potentiel d'1 V.",
        formula='E = e · U',
        formula_legend=[
            {'symbol': 'E',  'description': "Énergie acquise par la particule (en joules ou en eV)"},
            {'symbol': 'e',  'description': "Charge élémentaire (≈ 1,602 × 10⁻¹⁹ C)"},
            {'symbol': 'U',  'description': "Différence de potentiel traversée (en volts)"},
            {'symbol': 'eV', 'description': "Électron-volt : énergie acquise par 1 électron sous 1 V = 1,602 176 634 × 10⁻¹⁹ J"},
        ],
        history=[{'year': 1930, 'text': "Introduit en physique atomique pour des ordres de grandeur naturels."}],
        conversions=[
            {'from': '1 eV', 'to': '1,602 × 10⁻¹⁹ J'},
            {'from': '1 keV', 'to': '10³ eV (rayons X)'},
            {'from': '1 MeV', 'to': '10⁶ eV (radioactivité)'},
            {'from': '1 GeV', 'to': '10⁹ eV (accélérateurs)'},
            {'from': '1 TeV', 'to': '10¹² eV (LHC ≈ 13 TeV)'},
        ],
        pitfalls=[
            "Énergie au repos : E = mc². Pour un électron, mc² ≈ 511 keV.",
            "Les physiciens parlent souvent de masse en eV/c² : un proton « pèse » 938 MeV/c².",
        ]),
    _u('bar', 'bar', 'Bar', 'Pression', 'accepted', 44,
        definition="Égal à 100 000 Pa (10⁵ Pa) - proche de la pression atmosphérique moyenne.",
        formula='1 bar = 10⁵ Pa = 100 kPa',
        formula_legend=[
            {'symbol': 'bar', 'description': "Bar - unité de pression hors-SI, proche de l'atmosphère terrestre au niveau de la mer"},
            {'symbol': 'Pa',  'description': "Pascal - unité SI de pression"},
            {'symbol': 'kPa', 'description': "Kilopascal (1 000 Pa) - souvent utilisé en météorologie et en mécanique"},
        ],
        history=[{'year': 1909, 'text': "Vilhelm Bjerknes propose l'unité en météorologie."}],
        conversions=[
            {'from': '1 bar', 'to': '100 000 Pa = 750,06 mmHg'},
            {'from': '1 atm', 'to': '1,013 25 bar'},
            {'from': '1 mbar', 'to': '1 hPa (météo)'},
        ],
        pitfalls=["Bar : pression absolue ou relative selon contexte (pneus : « 2,5 bar » = relatif à atm)."]),
]
